"""Generate English and Korean paper summary Excel files for 24 reference papers."""
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# ── English data ──────────────────────────────────────────────────────────────
EN = [
  {
    "Abb.": "IMMAX",
    "Title": "Balancing Scales: Theoretical Framework for Imbalanced Classification",
    "Codes": "",
    "Motivation": "Standard loss functions lack theoretical guarantees under class imbalance",
    "Goal": "Derive H-consistency bounds for imbalanced margin losses; propose IMMAX algorithm",
    "Key methods": "Class-imbalanced margin loss; H-consistency bounds analysis; IMMAX algorithm",
    "Eval-Data": "CIFAR-10/100, standard classification benchmarks",
    "Eval-Comparison Models": "CE loss, cost-sensitive variants, re-weighting baselines",
    "Eval-Experiments": "Imbalanced multi-class classification under varying IR",
    "Metrics": "Accuracy, balanced accuracy, F1",
    "Key findings": "IMMAX achieves tighter theoretical bounds and competitive empirical performance over CE-based methods",
    "Limitations": "Framework assumes standard classification; applicability to regression/detection unclear",
    "Source": "ICML 2025",
    "Year": 2025,
  },
  {
    "Abb.": "LSR",
    "Title": "Latent Score-based Reweighting for Long-tailed Tabular Data",
    "Codes": "github.com/YunzeTong/latent-score-based-reweighting",
    "Motivation": "SMOTE introduces noise; density of minority regions in tabular data not exploited",
    "Goal": "Reweight training samples by estimated density in VAE latent space to upweight underrepresented regions",
    "Key methods": "VAE encoder; diffusion model for latent density estimation; density-based sample reweighting",
    "Eval-Data": "Multiple tabular classification benchmarks",
    "Eval-Comparison Models": "SMOTE, ADASYN, class-reweighting, ROS/RUS",
    "Eval-Experiments": "Binary/multiclass tabular imbalanced classification",
    "Metrics": "AUC, balanced accuracy, F1",
    "Key findings": "Outperforms SMOTE on low-density minority regions; VAE latent space better captures inter-class structure",
    "Limitations": "Requires training VAE + diffusion model; computationally expensive for large tabular data",
    "Source": "ICML 2025",
    "Year": 2025,
  },
  {
    "Abb.": "PRIME",
    "Title": "PRIME: Proxy-based Representation for Imbalanced Regression",
    "Codes": "",
    "Motivation": "Imbalanced regression underexplored; ordinal structure of target ignored",
    "Goal": "Learn better representations for deep imbalanced regression (DIR) via proxy and alignment losses",
    "Key methods": "Ordinal-aware proxy loss; alignment loss between proxies and features; applicable to DIR tasks",
    "Eval-Data": "Age estimation (IMDB-WIKI), depth estimation (NYU-v2), stem cell count (SCI)",
    "Eval-Comparison Models": "DIR, RankSim, ConR, FDS, LDS",
    "Eval-Experiments": "Deep imbalanced regression tasks with varying label density",
    "Metrics": "MAE, RMSE, geometric mean (GM)",
    "Key findings": "PRIME improves tail-range performance while maintaining head accuracy; proxy loss captures ordinal proximity",
    "Limitations": "Assumes ordinal/continuous target structure; proxy design requires domain knowledge",
    "Source": "ICML 2025",
    "Year": 2025,
  },
  {
    "Abb.": "DP",
    "Title": "Differential Privacy under Class Imbalance",
    "Codes": "",
    "Motivation": "DP mechanisms further degrade tail-class performance in imbalanced settings",
    "Goal": "Evaluate DP variants under class imbalance; identify which DP approaches preserve minority-class utility",
    "Key methods": "DP pre-processing (DP-SMOTE); DP in-processing (DP-SGD variants); private synthetic data generation",
    "Eval-Data": "Standard classification benchmarks at varying IR",
    "Eval-Comparison Models": "DP-SGD, standard SMOTE+DP, non-private baselines",
    "Eval-Experiments": "Binary/multiclass DP learning experiments with varying ε and IR",
    "Metrics": "Accuracy, recall, F1 per class; privacy budget ε",
    "Key findings": "Private synthetic data generation outperforms DP-SMOTE; in-processing DP-SGD insufficient alone for tail classes",
    "Limitations": "Privacy-utility tradeoff remains; synthetic data quality degrades at low ε",
    "Source": "ICML 2025",
    "Year": 2025,
  },
  {
    "Abb.": "DIRECT",
    "Title": "DIRECT: Active Learning under Imbalance and Label Noise",
    "Codes": "",
    "Motivation": "Active learning ignores simultaneous class imbalance and label noise; annotation cost high",
    "Goal": "Reduce annotation budget while handling imbalance + noise via optimal separation threshold",
    "Key methods": "Optimal separation threshold; dual-criteria sample selection; noise-aware query strategy",
    "Eval-Data": "Standard imbalanced classification benchmarks with synthetic noise",
    "Eval-Comparison Models": "BADGE, CoreSet, VAAL, CLUE, random sampling",
    "Eval-Experiments": "Active learning under varying IR and noise rates with fixed annotation budgets",
    "Metrics": "Balanced accuracy, annotation cost reduction (%)",
    "Key findings": "DIRECT reduces annotation cost 60%+ vs SOTA; threshold approach robust to noise and imbalance simultaneously",
    "Limitations": "Threshold tuning required; assumes some knowledge of noise model",
    "Source": "ICML 2025",
    "Year": 2025,
  },
  {
    "Abb.": "DCE",
    "Title": "Dual-Balance Collaborative Experts for Domain-Incremental Learning",
    "Codes": "github.com/Lain810/DCE",
    "Motivation": "Domain-incremental learning and intra-domain class imbalance compound each other; no method addresses both",
    "Goal": "Jointly tackle cross-domain shift and intra-domain class imbalance in domain-incremental learning",
    "Key methods": "3 frequency-aware experts (head/balanced/tail); DES router via Gaussian pseudo-sampling from class centroids/covariances; affinity matrix for expert collaboration",
    "Eval-Data": "Office-Home, DomainNet, CORe50, CDDB-Hard",
    "Eval-Comparison Models": "EWC, DER, FOSTER, iCaRL, BEEF, CoRe, GKEAL",
    "Eval-Experiments": "Domain-incremental learning on multi-domain benchmarks with natural/synthetic imbalance",
    "Metrics": "Overall accuracy, balanced accuracy, per-domain accuracy",
    "Key findings": "Outperforms SOTA on all 4 benchmarks; DES effectively routes rare-class samples to tail expert",
    "Limitations": "Gaussian pseudo-sampling assumes unimodal class distributions; head/tail threshold is a hyperparameter",
    "Source": "ICML 2025",
    "Year": 2025,
  },
  {
    "Abb.": "IP2SL",
    "Title": "IP2SL: Informative and Positive-Balanced Sampling for Long-tail Learning",
    "Codes": "",
    "Motivation": "Random oversampling creates redundant/uninformative samples; MI not maximized in existing samplers",
    "Goal": "Two-stage sampling maximizing mutual information and ensuring positive balance for long-tail",
    "Key methods": "BNS (Balanced Negative Sampling via MI maximization); IP-DPP (informative subset via Determinantal Point Processes)",
    "Eval-Data": "CIFAR-10-LT, CIFAR-100-LT, ImageNet-LT",
    "Eval-Comparison Models": "SMOTE, MixUp, BalancedSoftmax, LDAM, RIDE",
    "Eval-Experiments": "Long-tail image classification; ablation on BNS vs IP-DPP contribution",
    "Metrics": "Accuracy (many/medium/few), balanced accuracy",
    "Key findings": "IP2SL significantly outperforms random oversampling; BNS+IP-DPP synergistic; tail classes most improved",
    "Limitations": "DPP computation O(n³) expensive for large datasets; MI estimation requires large memory",
    "Source": "NeurIPS 2025",
    "Year": 2025,
  },
  {
    "Abb.": "MORE",
    "Title": "MORE: Model Rebalancing for Multi-label Long-tail Recognition",
    "Codes": "",
    "Motivation": "Multi-label LT underexplored; existing single-label rebalancing fails for multi-label co-occurrence",
    "Goal": "Plug-and-play rebalancing for multi-label long-tail classification via low-rank parameter decomposition",
    "Key methods": "Low-rank decomposition θ = θ^g ⊕ θ^t (global + tail-specific); sinusoidal reweighting schedule",
    "Eval-Data": "COCO-LT, VOC-LT, nuImages",
    "Eval-Comparison Models": "ASL, BCE, ResLT, DisAlign, OLTR",
    "Eval-Experiments": "Multi-label LT classification; plug-in ablations with existing methods",
    "Metrics": "mAP (head/medium/tail/overall)",
    "Key findings": "MORE improves tail mAP significantly; compatible with any multi-label classifier; minimal overhead",
    "Limitations": "Low-rank approximation may reduce capacity; sinusoidal schedule hyperparameter-sensitive",
    "Source": "NeurIPS 2025",
    "Year": 2025,
  },
  {
    "Abb.": "ImOOD",
    "Title": "ImOOD: Towards Balanced OOD Detection under Long-tailed Training Data",
    "Codes": "github.com/alibaba/imood",
    "Motivation": "OOD detection methods biased toward head classes under imbalanced training; tail-class OOD unreliable",
    "Goal": "Unified OOD detection under class imbalance without sacrificing ID classification accuracy",
    "Key methods": "Class-aware bias term between balanced/imbalanced OOD scores; training-time regularization",
    "Eval-Data": "CIFAR-10-LT, CIFAR-100-LT, ImageNet-LT + OOD sets (SVHN, LSUN, iSUN)",
    "Eval-Comparison Models": "ODIN, Energy, VOS, LogitAdj, GDFR",
    "Eval-Experiments": "OOD detection under varying IR; ID classification accuracy retention analysis",
    "Metrics": "AUROC, FPR95, AUPR; ID accuracy",
    "Key findings": "Improves OOD detection especially for tail-class inputs; training-time approach avoids test-time overhead",
    "Limitations": "Bias term requires balanced reference distribution; difficult to calibrate for extreme IR",
    "Source": "NeurIPS 2024",
    "Year": 2024,
  },
  {
    "Abb.": "PRL",
    "Title": "PRL: Controllable Long-tail Learning via Preference Representation Learning",
    "Codes": "github.com/DataLab-atom/PRL",
    "Motivation": "Fixed LT methods can't adapt head-tail trade-off; users need flexible control without retraining",
    "Goal": "Enable flexible and continuous head-tail performance trade-off at inference time",
    "Key methods": "Hypernetwork-generated diverse experts; Dirichlet distribution for preference vectors; expert ensemble at inference",
    "Eval-Data": "CIFAR-10-LT, CIFAR-100-LT, ImageNet-LT",
    "Eval-Comparison Models": "LDAM, BalancedSoftmax, MiSLAS, DisAlign, BCL",
    "Eval-Experiments": "LT classification with varying preference vectors; Pareto frontier analysis",
    "Metrics": "Accuracy (many/medium/few), balanced accuracy, Pareto frontier coverage",
    "Key findings": "Smooth head-tail trade-off via preference sampling; hypernetwork generalizes across preference space",
    "Limitations": "Hypernetwork adds parameters and training complexity; Dirichlet sampling sensitivity",
    "Source": "NeurIPS 2024",
    "Year": 2024,
  },
  {
    "Abb.": "NCMC",
    "Title": "Neural Collapse To Multiple Centers For Imbalanced Data",
    "Codes": "",
    "Motivation": "Standard NC collapses minority features to single center; fixed ETF classifiers don't outperform learnable ones",
    "Goal": "Design GCR and Cosine Loss to induce Neural Collapse to Multiple Centers (NCMC) for imbalanced learning",
    "Key methods": "GCR (Generalized Classification Rule); UFM + MSE-type loss analysis; Cosine Loss for fixed classifiers; class-aware center count strategy",
    "Eval-Data": "CIFAR-10, CIFAR-100",
    "Eval-Comparison Models": "LDAM, KCL, ARBLoss, ETF, ARB, standard CE",
    "Eval-Experiments": "LT classification with fixed vs. learnable classifiers; UFM theoretical analysis",
    "Metrics": "Accuracy (head/medium/tail), balanced accuracy",
    "Key findings": "NCMC Cosine Loss matches SOTA; multiple centers allow minority features to align across more directions",
    "Limitations": "Multiple center count requires heuristic strategy; UFM assumes unconstrained features",
    "Source": "NeurIPS 2024",
    "Year": 2024,
  },
  {
    "Abb.": "LLM-AutoDA",
    "Title": "LLM-AutoDA: LLM-Driven Automatic Data Augmentation for Long-tailed Problems",
    "Codes": "github.com/DataLab-atom/LLM-LT-AUG",
    "Motivation": "Manual DA strategies suboptimal and not adaptive; fixed strategies can't respond to training dynamics",
    "Goal": "Automate discovery of optimal class-wise DA strategies for long-tail data via LLMs",
    "Key methods": "LLM as augmentation strategy generator; val-performance reward signal; iterative strategy refinement; class-wise statistics guide LLM prompts",
    "Eval-Data": "CIFAR-10-LT, CIFAR-100-LT, ImageNet-LT, multiple LT benchmarks",
    "Eval-Comparison Models": "AutoAugment, CUDA, DODA, RandAugment, rebalancing baselines",
    "Eval-Experiments": "LT classification with automated DA search; strategy analysis and ablation",
    "Metrics": "Accuracy (many/medium/few), overall accuracy",
    "Key findings": "LLM-AutoDA outperforms manual DA and rebalancing methods; discovers novel effective strategies",
    "Limitations": "LLM API cost and latency; strategies may not generalize cross-dataset; slow iterative refinement",
    "Source": "NeurIPS 2024",
    "Year": 2024,
  },
  {
    "Abb.": "EPIC",
    "Title": "EPIC: Effective Prompting for Imbalanced-Class Tabular Data Synthesis via LLMs",
    "Codes": "github.com/seharanul17/EPIC (inferred from paper)",
    "Motivation": "LLMs struggle to generate high-quality minority tabular samples; prompt design unexplored for imbalanced tabular",
    "Goal": "Identify effective prompt designs for LLM-based imbalanced tabular data synthesis",
    "Key methods": "CSV-style balanced grouped prompting; unique variable mapping (random alphanumeric tokens); class-balanced example grouping in context",
    "Eval-Data": "6 real-world tabular datasets (Travel, Adult, etc.) + toy dataset",
    "Eval-Comparison Models": "GReaT, TabDDPM, CTGAN, CopulaGAN, TVAE, CTABGAN",
    "Eval-Experiments": "Tabular data synthesis quality evaluation + downstream ML classification on imbalanced data",
    "Metrics": "Specificity, Sensitivity; downstream classifier accuracy (XGBoost, CatBoost, LightGBM, GBM)",
    "Key findings": "EPIC achieves high specificity AND sensitivity simultaneously; outperforms fine-tuned GReaT; model-agnostic",
    "Limitations": "Relies on GPT-3.5 API; prompt design may need per-dataset adaptation; slower than direct generative models",
    "Source": "NeurIPS 2024",
    "Year": 2024,
  },
  {
    "Abb.": "DiffMatch",
    "Title": "Towards Unbiased Learning in Semi-supervised Semantic Segmentation",
    "Codes": "github.com/yuisuen/DiffMatch",
    "Motivation": "Discriminative pseudo-label methods suffer Matthew effect: head-class bias degrades tail-class pseudo labels",
    "Goal": "Mitigate Matthew effect in semi-supervised segmentation via generative diffusion model perspective",
    "Key methods": "Semi-sup segmentation as conditional discrete data generation; denoising diffusion process for pseudo-label; debiased adjustment to reverse conditional probability",
    "Eval-Data": "Cityscapes, PASCAL VOC (1/16 and 1/4 label protocols)",
    "Eval-Comparison Models": "UniMatch, DDFP, RankMatch, U²PL, AEL",
    "Eval-Experiments": "Semi-supervised semantic segmentation under limited label and class imbalance scenarios",
    "Metrics": "mIoU (head/tail classes separately), overall mIoU",
    "Key findings": "+2.6%/+2.0% over DDFP/RankMatch; head class retained; tail class significantly improved",
    "Limitations": "Diffusion inference slower than discriminative methods; debiasing calibration sensitive to distribution estimate",
    "Source": "ICLR 2025",
    "Year": 2025,
  },
  {
    "Abb.": "TTC",
    "Title": "A Tale of Two Classes: Adapting SupCon to Binary Imbalanced Datasets",
    "Codes": "github.com/aiforvision/TTC",
    "Motivation": "SupCon collapses minority embeddings to a single point in binary imbalanced settings; no prior study on this",
    "Goal": "Diagnose SupCon failure in binary imbalance; propose new metrics and fixes",
    "Key methods": "SAA (Sample Alignment Accuracy) + CAC (Class Alignment Consistency) diagnostic metrics; two new SupCon strategies for binary imbalance",
    "Eval-Data": "7 binary natural and medical imaging datasets (varying IR)",
    "Eval-Comparison Models": "SupCon, CE, LDAM, BCL, SimCLR",
    "Eval-Experiments": "Binary classification with increasing IR; representation space analysis via SAA/CAC",
    "Metrics": "AUC, balanced accuracy, SAA, CAC",
    "Key findings": "SupCon fails progressively with IR increase; proposed fixes boost accuracy up to +35% over SupCon and +5% over SOTA",
    "Limitations": "Binary-specific analysis; not validated on multi-class LT settings",
    "Source": "CVPR 2025",
    "Year": 2025,
  },
  {
    "Abb.": "LFN",
    "Title": "Learning from Neighbors: Category Extrapolation for Long-Tail Learning",
    "Codes": "shizhen-zhao.github.io/LT_Neighbors/",
    "Motivation": "Tail classes lack samples; datasets with finer granularity are less affected by imbalance",
    "Goal": "Improve tail representation via open-set auxiliary categories from LLM-driven web crawling",
    "Key methods": "LLM-based auxiliary category discovery (fine-grained related classes); automated web image crawling; neighbor-silencing loss; auxiliary classifier masking at inference",
    "Eval-Data": "ImageNet-LT, iNat18; pilot study on ImageNet-21k and OpenImage",
    "Eval-Comparison Models": "BalancedSoftmax, RIDE, ResLT, MiSLAS, DINOv2-based baselines",
    "Eval-Experiments": "LT classification with auxiliary data; granularity vs. imbalance pilot study",
    "Metrics": "Accuracy (many/medium/few), overall accuracy",
    "Key findings": "Category extrapolation consistently improves all class frequencies; finer granularity reliably reduces imbalance gap",
    "Limitations": "Web image quality variable; auxiliary data acquisition pipeline is complex and dataset-dependent",
    "Source": "CVPR 2025",
    "Year": 2025,
  },
  {
    "Abb.": "ADR",
    "Title": "From Head to Tail: Balanced Representation in LVLMs via Adaptive Data Calibration",
    "Codes": "",
    "Motivation": "LVLMs trained on long-tail instruction data over-represent head concepts; tail visual concepts underperform",
    "Goal": "Mitigate LT problem in LVLM training without increasing data volume",
    "Key methods": "3-stage ADR: (1) Analyzing Stage (token/object/co-occurrence/interrogation distributions), (2) Data Rebalancing (filter redundant head), (3) Data Synthesis (DDPM for tail)",
    "Eval-Data": "LLaVA training data; 11 VQA/VL benchmarks (MME, POPE, VQAV2, etc.)",
    "Eval-Comparison Models": "LLaVA 1.5, ShareGPT4V, ALLaVA, Mini-GPT4V",
    "Eval-Experiments": "LVLM evaluation on VQA, visual reasoning, hallucination, and tail-concept benchmarks",
    "Metrics": "MME score, POPE accuracy, VQA accuracy; tail-30% concept accuracy",
    "Key findings": "+4.36% avg over LLaVA 1.5 across 11 benchmarks without adding training data; tail concepts significantly improved",
    "Limitations": "Entity-level analysis may miss complex relational imbalances; DDPM tail synthesis quality varies",
    "Source": "CVPR 2025",
    "Year": 2025,
  },
  {
    "Abb.": "TAET",
    "Title": "TAET: Two-Stage Adversarial Equalization Training on Long-Tailed Distributions",
    "Codes": "github.com/BuhuiOK/TAET-Two-Stage-Adversarial-Equalization-Training-on-Long-Tailed-Distributions",
    "Motivation": "Adversarial training on long-tail data fails for tail classes; AT-BSL suffers from robustness overfitting on rare classes",
    "Goal": "Achieve balanced adversarial robustness across head and tail classes in long-tail distributions",
    "Key methods": "Two-stage: CE stabilization phase + HARL (Hierarchical Adversarial Robust Learning); Balanced Robustness metric",
    "Eval-Data": "CIFAR-10-LT, CIFAR-100-LT",
    "Eval-Comparison Models": "AT-BSL, TRADES, RoBal, MART, LAS-AT, GAIRAT, HE",
    "Eval-Experiments": "Adversarial training on LT datasets; PGD-20 attack evaluation; robustness-accuracy trade-off analysis",
    "Metrics": "Balanced Accuracy (clean + adversarial), Balanced Robustness",
    "Key findings": "TAET outperforms AT-BSL in balanced accuracy and tail robustness; memory-efficient two-stage design",
    "Limitations": "Only tested on CIFAR; AT still computationally expensive; two-stage schedule requires tuning",
    "Source": "CVPR 2025",
    "Year": 2025,
  },
  {
    "Abb.": "TinyChange",
    "Title": "A Tiny Change, A Giant Leap: LT Class-Incremental Learning via Geometric Prototype Alignment",
    "Codes": "github.com/laixinyi023/Geometric-Prototype-Alignment",
    "Motivation": "LT-CIL suffers gradient competition from head classes and catastrophic forgetting; random classifier init causes misalignment",
    "Goal": "Mitigate temporal bias (forgetting) and structural bias (head dominance) in long-tailed class-incremental learning",
    "Key methods": "GPA: (1) frozen prototype estimation, (2) geometric weight initialization on unit hypersphere (Fisher criterion), (3) Dynamic Anchoring Optimization",
    "Eval-Data": "CIFAR-100-LT, ImageNet-LT, ImageNet-R",
    "Eval-Comparison Models": "LU-CIR, DualPrompt, DER, iCaRL, EASE, RPAC, Gradient Reweighting",
    "Eval-Experiments": "LT class-incremental learning; plug-and-play ablation with 10 CIL frameworks",
    "Metrics": "Avg incremental accuracy, forgetting rate, tail class precision",
    "Key findings": "+6.11% avg accuracy, -6.38% forgetting on CIFAR-100-LT; 2.7× convergence acceleration; plug-and-play",
    "Limitations": "Prototype quality depends on frozen pretrained features; assumes feature extractor quality sufficient",
    "Source": "ICCV 2025",
    "Year": 2025,
  },
  {
    "Abb.": "MGS",
    "Title": "Long-Tailed Classification with Multi-Granularity Semantics",
    "Codes": "",
    "Motivation": "Head-to-tail knowledge transfer ignores class differences; fixed label hierarchy misses cross-subtree similarities",
    "Goal": "Discover implicit semantic similarities across classes for multi-granularity knowledge transfer in LT recognition",
    "Key methods": "LLM-generated multi-level class descriptions; sentence-transformer semantic similarity matrix; multi-granularity semantic knowledge graph; SKCL (semantic knowledge-driven contrastive learning)",
    "Eval-Data": "CIFAR-10-LT, CIFAR-100-LT, ImageNet-LT",
    "Eval-Comparison Models": "BCL, TSC, MiSLAS, PaCo, BalancedSoftmax, LLM-AutoDA",
    "Eval-Experiments": "LT classification; semantic similarity analysis; ablation on granularity levels",
    "Metrics": "Accuracy (many/medium/few), overall accuracy",
    "Key findings": "SKCL improves tail accuracy without compromising head; multi-granularity beats fixed hierarchy",
    "Limitations": "LLM descriptions may be noisy; sentence-transformer may miss visual nuance not captured in text",
    "Source": "ICCV 2025",
    "Year": 2025,
  },
  {
    "Abb.": "NodeImport",
    "Title": "NodeImport: Imbalanced Node Classification with Node Importance Assessment",
    "Codes": "github.com/NanChanNN/NodeImport",
    "Motivation": "GNNs overfit majority nodes; existing methods treat all minority nodes equally, ignoring intra-class differences and graph structure",
    "Goal": "Identify and prioritize valuable training nodes via importance assessment using balanced meta-sets",
    "Key methods": "Balanced meta-set for importance scoring; tractable importance formula η_v (no extra model needed); framework supports labeled/unlabeled/synthetic nodes; clustering-based meta-set construction",
    "Eval-Data": "3 citation datasets (Cora, Citeseer, etc.), 2 Amazon co-purchase datasets",
    "Eval-Comparison Models": "GCN, GAT, GraphSAGE + oversampling/reweighting (GraphSMOTE, ImGAGN, TAM)",
    "Eval-Experiments": "Node classification on imbalanced graphs; importance formula ablation; varying IR study",
    "Metrics": "Macro-F1, balanced accuracy, per-class F1",
    "Key findings": "NodeImport outperforms SOTA; importance formula naturally provides filtering threshold; adaptable to any node generator",
    "Limitations": "Meta-set quality sensitive to extreme class imbalance; bi-level approximation loses some precision",
    "Source": "KDD 2025",
    "Year": 2025,
  },
  {
    "Abb.": "ORD",
    "Title": "Synthetic Tabular Data Generation for Imbalanced Classification: Effectiveness of an Overlap Class",
    "Codes": "github.com/Annie2603/ORD",
    "Motivation": "Deep generative models produce lower-quality minority samples in imbalanced settings; overlap region degrades generation",
    "Goal": "Improve generative model quality for minority class by identifying and handling the majority-minority overlap region",
    "Key methods": "ORD (Overlap Region Detection): k-fold CV random forest to identify overlapping majority instances → ternary labeling (minority/overlap/clear majority) → conditional generation → train classifier excluding overlap",
    "Eval-Data": "4 real-life tabular datasets; 5 generative models (CTGAN, TabDDPM, ForestFlow, TabSyn, GReaT); 5 classifiers",
    "Eval-Comparison Models": "SMOTE, CTGAN, TabDDPM, ForestFlow, TabSyn baseline (without ORD)",
    "Eval-Experiments": "Imbalanced binary tabular classification with synthetic augmentation; ablation on each ORD component",
    "Metrics": "Specificity, Sensitivity, overall accuracy; Oracle Bayesian accuracy",
    "Key findings": "ORD improves both generator quality and classifier accuracy; compatible with all tested generators",
    "Limitations": "k-fold CV adds training overhead; designed for binary imbalance; threshold τ requires tuning",
    "Source": "AAAI 2025",
    "Year": 2025,
  },
  {
    "Abb.": "DBM",
    "Title": "Difficulty-aware Balancing Margin Loss for Long-tailed Recognition",
    "Codes": "github.com/quotation2520/dbm_ltr",
    "Motivation": "Class-level rebalancing ignores instance-level difficulty; hard samples within classes under-addressed",
    "Goal": "Jointly address class imbalance and instance difficulty via a dual-component margin loss",
    "Key methods": "DBM loss = class-wise margin (∝ class frequency) + instance-wise margin (angular distance to class center for hard positives)",
    "Eval-Data": "CIFAR-10-LT, CIFAR-100-LT, ImageNet-LT, iNaturalist2018",
    "Eval-Comparison Models": "LDAM, BalancedSoftmax, BCL, MiSLAS, PaCo, LogitAdj",
    "Eval-Experiments": "LT image classification; ablation on class-wise vs. instance-wise margins; plug-in with existing methods",
    "Metrics": "Accuracy (many/medium/few), overall accuracy",
    "Key findings": "DBM consistently improves when combined with existing LT methods; instance-wise margin crucial for hard positive samples",
    "Limitations": "Angular distance per sample adds overhead; two margin components require careful tuning",
    "Source": "AAAI 2025",
    "Year": 2025,
  },
  {
    "Abb.": "BCE3S",
    "Title": "BCE3S: Binary Cross-Entropy Based Tripartite Synergistic Learning for Long-tailed Recognition",
    "Codes": "github.com/wakinghours-github/BCE3S",
    "Motivation": "CE-Softmax couples imbalanced classifier vectors amplifying imbalance; BCE decouples metrics but TSL with BCE unexplored",
    "Goal": "Design BCE-based tripartite synergistic learning integrating joint learning, contrastive learning, and uniform classifier learning",
    "Key methods": "BCE3S = L_sc_bce (joint feature-classifier BCE) + L_ss_bce (BCE-based contrastive) + L_cc_bce (BCE-based uniform classifier separability)",
    "Eval-Data": "CIFAR-10-LT, CIFAR-100-LT, ImageNet-LT, iNaturalist2018",
    "Eval-Comparison Models": "CB Loss, RIDE, BCL, DisCo, ETF, RBL, NC-cRT",
    "Eval-Experiments": "LT classification at various IF; ablation on each BCE component; comparison to all three TSL modes",
    "Metrics": "Accuracy (many/medium/few), overall accuracy",
    "Key findings": "SOTA 59.50% on CIFAR-100-LT IF=100; BCE uniform learning effectively balances classifier separability",
    "Limitations": "BCE-based training more complex than CE; three-component loss requires careful tuning of relative weights",
    "Source": "AAAI 2026 (arXiv Nov 2025)",
    "Year": 2026,
  },
]

# ── Korean data ───────────────────────────────────────────────────────────────
KO = [
  {
    "약어": "IMMAX",
    "제목": "Balancing Scales: 불균형 분류를 위한 이론적 프레임워크",
    "코드": "",
    "동기": "표준 손실 함수는 클래스 불균형 하에서 이론적 보장이 부족함",
    "목표": "불균형 마진 손실에 대한 H-일관성 경계 도출 및 IMMAX 알고리즘 제안",
    "핵심 방법": "클래스 불균형 마진 손실; H-일관성 경계 분석; IMMAX 알고리즘",
    "평가-데이터": "CIFAR-10/100, 표준 분류 벤치마크",
    "평가-비교 모델": "CE 손실, 비용 민감 변형, 재가중 기준선",
    "평가-실험 내용": "다양한 IR에서 불균형 다중 클래스 분류",
    "지표": "정확도, 균형 정확도, F1",
    "주요 발견 및 기여": "IMMAX는 CE 기반 방법 대비 더 타이트한 이론적 경계와 경쟁력 있는 성능 달성",
    "한계": "표준 분류를 가정; 회귀/검출 확장 불분명",
    "출처": "ICML 2025",
    "연도": 2025,
  },
  {
    "약어": "LSR",
    "제목": "긴 꼬리 테이블형 데이터를 위한 잠재 점수 기반 재가중",
    "코드": "github.com/YunzeTong/latent-score-based-reweighting",
    "동기": "SMOTE는 노이즈를 유발; 테이블형 데이터의 소수 클래스 잠재 밀도를 활용하지 못함",
    "목표": "VAE 잠재 공간의 밀도 추정을 통해 저밀도 소수 클래스 영역에 가중치 부여",
    "핵심 방법": "VAE 인코더; 잠재 공간의 확산 모델 밀도 추정; 밀도 기반 샘플 재가중",
    "평가-데이터": "다수의 테이블형 분류 벤치마크",
    "평가-비교 모델": "SMOTE, ADASYN, 클래스 재가중, ROS/RUS",
    "평가-실험 내용": "이진/다중 클래스 테이블형 불균형 분류",
    "지표": "AUC, 균형 정확도, F1",
    "주요 발견 및 기여": "저밀도 소수 영역에서 SMOTE보다 우수; VAE 잠재 공간이 클래스 간 구조를 더 잘 포착",
    "한계": "VAE + 확산 모델 학습 필요; 대용량 테이블 데이터에 계산 비용 큼",
    "출처": "ICML 2025",
    "연도": 2025,
  },
  {
    "약어": "PRIME",
    "제목": "PRIME: 불균형 회귀를 위한 프록시 기반 표현 학습",
    "코드": "",
    "동기": "불균형 회귀가 미개척 영역; 목표값의 순서 구조가 무시됨",
    "목표": "프록시 및 정렬 손실을 통한 심층 불균형 회귀(DIR)의 표현 학습 개선",
    "핵심 방법": "순서 인식 프록시 손실; 프록시-특징 정렬 손실; DIR 태스크에 범용 적용",
    "평가-데이터": "나이 추정(IMDB-WIKI), 깊이 추정(NYU-v2), 줄기세포 계수(SCI)",
    "평가-비교 모델": "DIR, RankSim, ConR, FDS, LDS",
    "평가-실험 내용": "레이블 밀도가 다양한 심층 불균형 회귀 태스크",
    "지표": "MAE, RMSE, 기하 평균(GM)",
    "주요 발견 및 기여": "꼬리 범위 성능 향상; 프록시 손실이 순서적 근접성을 포착",
    "한계": "순서형/연속형 목표 구조 가정; 프록시 설계에 도메인 지식 필요",
    "출처": "ICML 2025",
    "연도": 2025,
  },
  {
    "약어": "DP",
    "제목": "클래스 불균형 하에서의 차등 프라이버시",
    "코드": "",
    "동기": "DP 메커니즘이 불균형 환경에서 꼬리 클래스 성능을 더욱 저하시킴",
    "목표": "불균형 환경에서 DP 변형을 평가하고, 소수 클래스 유용성을 보존하는 접근 식별",
    "핵심 방법": "DP 전처리(DP-SMOTE); DP 인-프로세싱(DP-SGD 변형); 비공개 합성 데이터 생성",
    "평가-데이터": "다양한 IR의 표준 분류 벤치마크",
    "평가-비교 모델": "DP-SGD, SMOTE+DP, 비공개 기준선",
    "평가-실험 내용": "ε 및 IR 변화에 따른 이진/다중 클래스 DP 학습 실험",
    "지표": "클래스별 정확도·재현율·F1; 프라이버시 예산 ε",
    "주요 발견 및 기여": "비공개 합성 데이터가 DP-SMOTE보다 우수; DP-SGD 단독으로는 꼬리 클래스에 불충분",
    "한계": "프라이버시-유용성 트레이드오프 유지; 낮은 ε에서 합성 품질 저하",
    "출처": "ICML 2025",
    "연도": 2025,
  },
  {
    "약어": "DIRECT",
    "제목": "DIRECT: 불균형 및 레이블 노이즈 환경에서의 능동 학습",
    "코드": "",
    "동기": "능동 학습이 클래스 불균형과 레이블 노이즈를 동시에 다루지 못함",
    "목표": "최적 분리 임계값으로 불균형+노이즈 환경에서 주석 비용 절감",
    "핵심 방법": "최적 분리 임계값; 이중 기준 샘플 선택; 노이즈 인식 쿼리 전략",
    "평가-데이터": "합성 노이즈를 적용한 표준 불균형 분류 벤치마크",
    "평가-비교 모델": "BADGE, CoreSet, VAAL, CLUE, 랜덤 샘플링",
    "평가-실험 내용": "고정 주석 예산 하에서 IR·노이즈 비율 변화 실험",
    "지표": "균형 정확도, 주석 비용 절감률(%)",
    "주요 발견 및 기여": "기존 SOTA 대비 주석 비용 60%+ 절감; 임계값 접근이 노이즈+불균형에 동시 강건",
    "한계": "임계값 튜닝 필요; 노이즈 모델에 대한 부분적 사전 지식 가정",
    "출처": "ICML 2025",
    "연도": 2025,
  },
  {
    "약어": "DCE",
    "제목": "도메인 점진적 학습을 위한 이중 균형 협력 전문가",
    "코드": "github.com/Lain810/DCE",
    "동기": "도메인 점진적 학습과 도메인 내 클래스 불균형이 서로 복합적으로 작용; 두 문제를 동시에 다루는 방법 없음",
    "목표": "도메인 이동과 도메인 내 클래스 불균형을 동시에 해결",
    "핵심 방법": "빈도 인식 3개 전문가(헤드/균형/꼬리); 클래스 중심·분산 가우시안 의사 샘플링 기반 DES 라우터; 친화 행렬로 전문가 협력",
    "평가-데이터": "Office-Home, DomainNet, CORe50, CDDB-Hard",
    "평가-비교 모델": "EWC, DER, FOSTER, iCaRL, BEEF, CoRe, GKEAL",
    "평가-실험 내용": "자연/합성 불균형을 가진 다중 도메인 벤치마크에서 도메인 점진적 학습",
    "지표": "전체 정확도, 균형 정확도, 도메인별 정확도",
    "주요 발견 및 기여": "4개 벤치마크 전체에서 SOTA 초과; DES가 희귀 클래스를 꼬리 전문가로 효과적 라우팅",
    "한계": "가우시안 의사 샘플링이 단봉 분포 가정; 헤드/꼬리 임계값이 하이퍼파라미터",
    "출처": "ICML 2025",
    "연도": 2025,
  },
  {
    "약어": "IP2SL",
    "제목": "IP2SL: 긴 꼬리 학습을 위한 정보성·양성 균형 샘플링",
    "코드": "",
    "동기": "랜덤 오버샘플링이 중복/비정보적 샘플을 생성; 기존 샘플러에서 MI 최대화 미흡",
    "목표": "상호 정보량 극대화와 양성 균형을 동시에 달성하는 2단계 샘플링",
    "핵심 방법": "BNS(MI 최대화 기반 균형 부정 샘플링); IP-DPP(행렬식 점 프로세스 기반 정보성 부분 집합 샘플링)",
    "평가-데이터": "CIFAR-10-LT, CIFAR-100-LT, ImageNet-LT",
    "평가-비교 모델": "SMOTE, MixUp, BalancedSoftmax, LDAM, RIDE",
    "평가-실험 내용": "긴 꼬리 이미지 분류; BNS vs. IP-DPP 기여도 절제 실험",
    "지표": "정확도(많음/중간/적음), 균형 정확도",
    "주요 발견 및 기여": "랜덤 오버샘플링 대비 큰 폭 향상; BNS+IP-DPP 시너지; 꼬리 클래스 개선 가장 큼",
    "한계": "DPP 계산 O(n³)로 대용량에 비용 큼; MI 추정에 큰 메모리 필요",
    "출처": "NeurIPS 2025",
    "연도": 2025,
  },
  {
    "약어": "MORE",
    "제목": "MORE: 다중 레이블 긴 꼬리 인식을 위한 모델 재균형",
    "코드": "",
    "동기": "다중 레이블 긴 꼬리 문제가 미개척; 단일 레이블 재균형이 공존 관계에서 실패",
    "목표": "저랭크 파라미터 분해를 통한 다중 레이블 긴 꼬리 분류의 플러그인 재균형",
    "핵심 방법": "저랭크 분해 θ = θ^g ⊕ θ^t (전역+꼬리 특화); 사인파형 재가중 스케줄",
    "평가-데이터": "COCO-LT, VOC-LT, nuImages",
    "평가-비교 모델": "ASL, BCE, ResLT, DisAlign, OLTR",
    "평가-실험 내용": "다중 레이블 긴 꼬리 분류; 기존 방법과의 플러그인 절제 실험",
    "지표": "mAP(헤드/중간/꼬리/전체)",
    "주요 발견 및 기여": "꼬리 mAP 유의미하게 향상; 임의 다중 레이블 분류기와 호환; 오버헤드 최소",
    "한계": "저랭크 근사로 복잡한 태스크에서 용량 손실 가능; 사인파 스케줄 하이퍼파라미터 민감",
    "출처": "NeurIPS 2025",
    "연도": 2025,
  },
  {
    "약어": "ImOOD",
    "제목": "ImOOD: 긴 꼬리 훈련 데이터 하에서의 균형 잡힌 OOD 탐지",
    "코드": "github.com/alibaba/imood",
    "동기": "OOD 탐지 방법이 불균형 훈련 시 헤드 클래스에 편향; 꼬리 클래스 OOD 탐지 불신뢰",
    "목표": "ID 분류 정확도를 유지하면서 클래스 불균형 하에서 통합 OOD 탐지",
    "핵심 방법": "균형/불균형 OOD 점수 간 클래스 인식 편향 항; 훈련 시 정규화",
    "평가-데이터": "CIFAR-10/100-LT, ImageNet-LT + OOD 집합(SVHN, LSUN, iSUN)",
    "평가-비교 모델": "ODIN, Energy, VOS, LogitAdj, GDFR",
    "평가-실험 내용": "다양한 IR에서 OOD 탐지; ID 정확도 유지 분석",
    "지표": "AUROC, FPR95, AUPR; ID 정확도",
    "주요 발견 및 기여": "꼬리 클래스 OOD 탐지 개선; 훈련 시 접근으로 테스트 오버헤드 없음",
    "한계": "편향 항이 균형 참조 분포 추정 필요; 극단적 IR에서 보정 어려움",
    "출처": "NeurIPS 2024",
    "연도": 2024,
  },
  {
    "약어": "PRL",
    "제목": "PRL: 선호도 표현 학습을 통한 제어 가능한 긴 꼬리 학습",
    "코드": "github.com/DataLab-atom/PRL",
    "동기": "고정된 LT 방법은 헤드-꼬리 트레이드오프 조정 불가; 재학습 없이 유연한 제어 필요",
    "목표": "추론 시 헤드-꼬리 성능 트레이드오프를 유연하게 조정",
    "핵심 방법": "하이퍼네트워크 기반 다양한 전문가 생성; 선호 벡터를 위한 디리클레 분포; 추론 시 전문가 앙상블",
    "평가-데이터": "CIFAR-10/100-LT, ImageNet-LT",
    "평가-비교 모델": "LDAM, BalancedSoftmax, MiSLAS, DisAlign, BCL",
    "평가-실험 내용": "다양한 선호 벡터 LT 분류; 파레토 프론티어 분석",
    "지표": "정확도(많음/중간/적음), 균형 정확도, 파레토 프론티어 커버리지",
    "주요 발견 및 기여": "선호 샘플링으로 부드러운 헤드-꼬리 트레이드오프; 하이퍼네트워크가 선호 공간 전반에 일반화",
    "한계": "하이퍼네트워크로 파라미터·학습 복잡도 증가; 디리클레 샘플링 민감도",
    "출처": "NeurIPS 2024",
    "연도": 2024,
  },
  {
    "약어": "NCMC",
    "제목": "불균형 데이터를 위한 다중 중심 신경 붕괴",
    "코드": "",
    "동기": "표준 NC는 소수 클래스 특징을 단일 중심으로 붕괴; 고정 ETF 분류기가 학습 가능 분류기보다 낫지 않음",
    "목표": "GCR 및 코사인 손실로 불균형 학습에서 다중 중심 신경 붕괴(NCMC) 유도",
    "핵심 방법": "GCR(일반화 분류 규칙); UFM + MSE 손실 분석; 고정 분류기를 위한 코사인 손실; 클래스별 중심 수 전략",
    "평가-데이터": "CIFAR-10, CIFAR-100",
    "평가-비교 모델": "LDAM, KCL, ARBLoss, ETF, ARB, 표준 CE",
    "평가-실험 내용": "고정 vs 학습 가능 분류기 LT 분류; UFM 이론 분석",
    "지표": "정확도(헤드/중간/꼬리), 균형 정확도",
    "주요 발견 및 기여": "NCMC 코사인 손실이 SOTA와 동등; 다중 중심으로 소수 클래스 특징이 더 많은 방향에 정렬",
    "한계": "다중 중심 수 결정에 휴리스틱 필요; UFM이 비제약 특징 가정",
    "출처": "NeurIPS 2024",
    "연도": 2024,
  },
  {
    "약어": "LLM-AutoDA",
    "제목": "LLM-AutoDA: 긴 꼬리 문제를 위한 LLM 기반 자동 데이터 증강",
    "코드": "github.com/DataLab-atom/LLM-LT-AUG",
    "동기": "수동 DA 전략이 최적화되지 않고 훈련 동역학에 적응 불가",
    "목표": "LLM을 활용해 긴 꼬리 데이터의 최적 클래스별 DA 전략을 자동으로 탐색",
    "핵심 방법": "LLM 기반 증강 전략 생성기; 검증 성능을 보상 신호로 활용; 반복적 전략 정제; 클래스별 통계로 LLM 프롬프트 생성",
    "평가-데이터": "CIFAR-10/100-LT, ImageNet-LT, 다수 LT 벤치마크",
    "평가-비교 모델": "AutoAugment, CUDA, DODA, RandAugment, 재균형 기준선",
    "평가-실험 내용": "자동화된 DA 전략 탐색을 통한 LT 분류; 전략 분석 및 절제 실험",
    "지표": "정확도(많음/중간/적음), 전체 정확도",
    "주요 발견 및 기여": "수동 DA 및 재균형 방법 대비 우수; 새로운 효과적 전략 발견",
    "한계": "LLM API 비용·지연; 전략의 데이터셋 간 일반화 불확실; 반복 정제 속도 느림",
    "출처": "NeurIPS 2024",
    "연도": 2024,
  },
  {
    "약어": "EPIC",
    "제목": "EPIC: LLM을 통한 불균형 클래스 테이블형 데이터 합성의 효과적 프롬프팅",
    "코드": "github.com/seharanul17/EPIC (추정)",
    "동기": "LLM이 불균형 테이블 데이터에서 고품질 소수 클래스 샘플 생성에 어려움; 프롬프트 설계 미개척",
    "목표": "불균형 테이블 데이터 합성을 위한 LLM 프롬프트 설계의 최적 요소 식별",
    "핵심 방법": "CSV 스타일 균형 그룹 프롬프팅; 고유 변수 매핑(랜덤 영숫자 토큰); 컨텍스트 내 클래스 균형 예시 그룹",
    "평가-데이터": "6개 실제 테이블 데이터셋(Travel, Adult 등) + 장난감 데이터셋",
    "평가-비교 모델": "GReaT, TabDDPM, CTGAN, CopulaGAN, TVAE, CTABGAN",
    "평가-실험 내용": "테이블 데이터 합성 품질 평가 + 불균형 데이터에서 하위 ML 분류",
    "지표": "특이도, 민감도; XGBoost·CatBoost·LightGBM·GBM 분류 정확도",
    "주요 발견 및 기여": "EPIC이 높은 특이도와 민감도를 동시에 달성; 파인튜닝된 GReaT보다 우수; 모델 비의존적",
    "한계": "GPT-3.5 API 의존; 데이터셋별 프롬프트 조정 필요; 직접 생성 모델보다 느림",
    "출처": "NeurIPS 2024",
    "연도": 2024,
  },
  {
    "약어": "DiffMatch",
    "제목": "반지도 시맨틱 분할에서의 편향 없는 학습",
    "코드": "github.com/yuisuen/DiffMatch",
    "동기": "판별적 의사 레이블 방법이 매튜 효과 유발; 헤드 클래스 편향이 꼬리 클래스 의사 레이블 저하",
    "목표": "생성적 확산 모델 관점으로 반지도 분할의 매튜 효과 완화",
    "핵심 방법": "반지도 분할을 조건부 이산 데이터 생성 문제로 정형화; 의사 레이블을 위한 노이즈 제거 확산; 역방향 조건부 확률의 편향 제거 보정",
    "평가-데이터": "Cityscapes, PASCAL VOC (1/16 및 1/4 레이블 프로토콜)",
    "평가-비교 모델": "UniMatch, DDFP, RankMatch, U²PL, AEL",
    "평가-실험 내용": "제한된 레이블 및 클래스 불균형 환경에서 반지도 시맨틱 분할",
    "지표": "mIoU(헤드/꼬리 클래스 별도), 전체 mIoU",
    "주요 발견 및 기여": "DDFP/RankMatch 대비 +2.6%/+2.0%; 헤드 성능 유지; 꼬리 클래스 대폭 향상",
    "한계": "확산 추론이 판별 방법보다 느림; 편향 보정이 분포 추정에 민감",
    "출처": "ICLR 2025",
    "연도": 2025,
  },
  {
    "약어": "TTC",
    "제목": "두 클래스 이야기: 이진 불균형 데이터셋에서의 SupCon 적응",
    "코드": "github.com/aiforvision/TTC",
    "동기": "SupCon이 이진 불균형 환경에서 소수 클래스 임베딩을 단일 점으로 붕괴; 선행 연구 없음",
    "목표": "이진 불균형에서 SupCon 실패를 진단하고 새로운 지표 및 수정안 제안",
    "핵심 방법": "SAA(샘플 정렬 정확도) + CAC(클래스 정렬 일관성) 진단 지표; 이진 불균형 전용 SupCon 변형 2가지",
    "평가-데이터": "7개 이진 자연·의료 영상 데이터셋(다양한 IR)",
    "평가-비교 모델": "SupCon, CE, LDAM, BCL, SimCLR",
    "평가-실험 내용": "IR 증가에 따른 이진 분류; SAA/CAC 지표로 표현 공간 분석",
    "지표": "AUC, 균형 정확도, SAA, CAC",
    "주요 발견 및 기여": "IR 증가에 따른 SupCon 점진적 실패 실증; 제안 수정이 SupCon 대비 최대 +35% 향상",
    "한계": "이진 분류 특화 분석; 다중 클래스 LT 환경 미검증",
    "출처": "CVPR 2025",
    "연도": 2025,
  },
  {
    "약어": "LFN",
    "제목": "이웃에서 배우기: 긴 꼬리 학습을 위한 카테고리 외삽",
    "코드": "shizhen-zhao.github.io/LT_Neighbors/",
    "동기": "꼬리 클래스에 샘플 부족; 세분성이 높은 데이터셋이 불균형 영향을 덜 받음",
    "목표": "LLM 기반 웹 크롤링으로 수집한 보조 카테고리를 통해 꼬리 표현 개선",
    "핵심 방법": "LLM 기반 보조 카테고리 탐색(세분화된 관련 클래스); 자동 웹 이미지 수집 파이프라인; 이웃 침묵 손실; 추론 시 보조 분류기 마스킹",
    "평가-데이터": "ImageNet-LT, iNat18; ImageNet-21k·OpenImage 파일럿 연구",
    "평가-비교 모델": "BalancedSoftmax, RIDE, ResLT, MiSLAS, DINOv2 기준선",
    "평가-실험 내용": "보조 데이터를 활용한 LT 분류; 세분성 vs. 불균형 파일럿 연구",
    "지표": "정확도(많음/중간/적음), 전체 정확도",
    "주요 발견 및 기여": "카테고리 외삽이 모든 클래스 빈도에서 일관되게 개선; 세분성 증가가 불균형 격차를 안정적으로 줄임",
    "한계": "웹 이미지 품질 가변적; 보조 데이터 수집 파이프라인이 복잡하고 데이터셋 의존적",
    "출처": "CVPR 2025",
    "연도": 2025,
  },
  {
    "약어": "ADR",
    "제목": "헤드에서 꼬리로: 적응형 데이터 보정을 통한 LVLM의 균형 표현",
    "코드": "",
    "동기": "LVLM의 지시 튜닝 데이터가 헤드 개념 과대표현; 꼬리 시각 개념 성능 저하",
    "목표": "데이터 양 증가 없이 LVLM 훈련에서 긴 꼬리 문제 완화",
    "핵심 방법": "3단계 ADR: (1) 분석 단계(토큰/객체/공존/질문 분포), (2) 데이터 재균형(헤드 중복 데이터 필터링), (3) 데이터 합성(꼬리를 위한 DDPM)",
    "평가-데이터": "LLaVA 훈련 데이터; 11개 VQA/VL 벤치마크(MME, POPE, VQAV2 등)",
    "평가-비교 모델": "LLaVA 1.5, ShareGPT4V, ALLaVA, Mini-GPT4V",
    "평가-실험 내용": "VQA, 시각 추론, 환각, 꼬리 개념 벤치마크에서 LVLM 평가",
    "지표": "MME 점수, POPE 정확도, VQA 정확도; 꼬리 30% 개념 정확도",
    "주요 발견 및 기여": "11개 벤치마크에서 LLaVA 1.5 대비 평균 +4.36%; 데이터 추가 없이 꼬리 개념 크게 향상",
    "한계": "개체 수준 분석이 복잡한 관계적 불균형 놓칠 수 있음; DDPM 꼬리 합성 품질 가변적",
    "출처": "CVPR 2025",
    "연도": 2025,
  },
  {
    "약어": "TAET",
    "제목": "TAET: 긴 꼬리 분포에서의 2단계 적대적 균등화 훈련",
    "코드": "github.com/BuhuiOK/TAET-...",
    "동기": "긴 꼬리 데이터에서 적대적 훈련이 꼬리 클래스에 실패; AT-BSL이 희귀 클래스에 견고성 과적합",
    "목표": "긴 꼬리 분포에서 헤드·꼬리 클래스 전반에 걸친 균형 잡힌 적대적 견고성 달성",
    "핵심 방법": "2단계: CE 안정화 단계 + HARL(계층적 적대적 견고 학습); 균형 견고성 지표",
    "평가-데이터": "CIFAR-10-LT, CIFAR-100-LT",
    "평가-비교 모델": "AT-BSL, TRADES, RoBal, MART, LAS-AT, GAIRAT, HE",
    "평가-실험 내용": "LT 데이터셋에서 적대적 훈련; PGD-20 공격 평가; 견고성-정확도 트레이드오프 분석",
    "지표": "균형 정확도(정상+적대), 균형 견고성",
    "주요 발견 및 기여": "TAET가 균형 정확도와 꼬리 견고성에서 AT-BSL 초과; 메모리 효율적 2단계 설계",
    "한계": "CIFAR 한정 실험; AT 자체의 계산 비용 큼; 2단계 일정 튜닝 필요",
    "출처": "CVPR 2025",
    "연도": 2025,
  },
  {
    "약어": "TinyChange",
    "제목": "작은 변화, 큰 도약: 기하학적 프로토타입 정렬을 통한 긴 꼬리 클래스 점진적 학습",
    "코드": "github.com/laixinyi023/Geometric-Prototype-Alignment",
    "동기": "LT-CIL에서 헤드 클래스로 인한 기울기 경쟁과 파국적 망각 발생; 랜덤 분류기 초기화가 정렬 불량 유발",
    "목표": "긴 꼬리 클래스 점진적 학습에서 시간적 편향(망각)과 구조적 편향(헤드 지배) 동시 완화",
    "핵심 방법": "GPA: (1) 동결 프로토타입 추정, (2) 단위 초구면 기하학적 가중치 초기화(피셔 기준), (3) 동적 앵커링 최적화",
    "평가-데이터": "CIFAR-100-LT, ImageNet-LT, ImageNet-R",
    "평가-비교 모델": "LU-CIR, DualPrompt, DER, iCaRL, EASE, RPAC, 기울기 재가중",
    "평가-실험 내용": "LT 클래스 점진적 학습; 10개 CIL 프레임워크와 플러그인 절제 실험",
    "지표": "평균 점진적 정확도, 망각률, 꼬리 클래스 정밀도",
    "주요 발견 및 기여": "CIFAR-100-LT에서 +6.11% 정확도, -6.38% 망각; 2.7× 수렴 가속; 플러그인 호환",
    "한계": "프로토타입 품질이 동결된 사전 학습 특징에 의존; 특징 추출기 품질 충분 가정",
    "출처": "ICCV 2025",
    "연도": 2025,
  },
  {
    "약어": "MGS",
    "제목": "다중 세분성 시맨틱을 활용한 긴 꼬리 분류",
    "코드": "",
    "동기": "헤드→꼬리 지식 전이가 클래스 차이를 무시; 고정 레이블 계층이 서브트리 간 유사성 놓침",
    "목표": "클래스 간 암묵적 시맨틱 유사성 발견으로 다중 세분성 지식 전이",
    "핵심 방법": "LLM 기반 다중 수준 클래스 설명 생성; 문장 변환기 시맨틱 유사도 행렬; 다중 세분성 시맨틱 지식 그래프; SKCL(시맨틱 지식 기반 대조 학습)",
    "평가-데이터": "CIFAR-10/100-LT, ImageNet-LT",
    "평가-비교 모델": "BCL, TSC, MiSLAS, PaCo, BalancedSoftmax, LLM-AutoDA",
    "평가-실험 내용": "LT 분류; 시맨틱 유사도 분석; 세분성 수준 절제 실험",
    "지표": "정확도(많음/중간/적음), 전체 정확도",
    "주요 발견 및 기여": "SKCL이 헤드 성능 유지하면서 꼬리 정확도 향상; 다중 세분성이 고정 계층보다 우수",
    "한계": "LLM 설명에 노이즈 가능; 문장 변환기가 텍스트에 포착되지 않는 시각 정보 놓칠 수 있음",
    "출처": "ICCV 2025",
    "연도": 2025,
  },
  {
    "약어": "NodeImport",
    "제목": "NodeImport: 노드 중요도 평가를 통한 불균형 노드 분류",
    "코드": "github.com/NanChanNN/NodeImport",
    "동기": "GNN이 다수 노드에 과적합; 기존 방법이 소수 노드를 동일하게 취급하여 개별 특성 무시",
    "목표": "균형 메타-셋을 활용한 중요도 평가로 유용한 훈련 노드를 식별·우선순위화",
    "핵심 방법": "중요도 점수를 위한 균형 메타-셋; 추가 모델 불필요한 처리 가능한 중요도 공식 η_v; 레이블/미레이블/합성 노드 지원; 클러스터링 기반 메타-셋 구성",
    "평가-데이터": "3개 인용 데이터셋(Cora 등), 2개 Amazon 공동 구매 데이터셋",
    "평가-비교 모델": "GCN, GAT, GraphSAGE + 오버샘플링/재가중(GraphSMOTE, ImGAGN, TAM)",
    "평가-실험 내용": "불균형 그래프 노드 분류; 중요도 공식 절제; 다양한 IR 연구",
    "지표": "매크로-F1, 균형 정확도, 클래스별 F1",
    "주요 발견 및 기여": "NodeImport가 모든 벤치마크에서 SOTA 초과; 중요도 공식이 자연스럽게 임계값 제공; 임의 노드 생성기에 적응 가능",
    "한계": "극단적 불균형에서 메타-셋 품질 민감; 이중 수준 근사로 정밀도 일부 손실",
    "출처": "KDD 2025",
    "연도": 2025,
  },
  {
    "약어": "ORD",
    "제목": "불균형 분류를 위한 합성 테이블형 데이터 생성: 중복 클래스의 놀라운 효과",
    "코드": "github.com/Annie2603/ORD",
    "동기": "심층 생성 모델이 불균형 환경에서 소수 클래스 샘플의 질 저하; 중복 영역이 생성 품질 저하",
    "목표": "다수-소수 클래스 중복 영역을 식별·처리하여 소수 클래스 합성 품질 개선",
    "핵심 방법": "ORD: k-폴드 CV 랜덤 포레스트로 중복 다수 인스턴스 식별 → 3중 레이블링(소수/중복/명확 다수) → 조건부 생성 → 중복 영역 제외 후 분류기 학습",
    "평가-데이터": "4개 실제 테이블 데이터셋; 5개 생성 모델; 5개 분류기",
    "평가-비교 모델": "SMOTE, CTGAN, TabDDPM, ForestFlow, TabSyn 기준선(ORD 없음)",
    "평가-실험 내용": "합성 증강을 활용한 불균형 이진 테이블 분류; ORD 구성요소 절제 실험",
    "지표": "특이도, 민감도, 전체 정확도; Oracle Bayesian 정확도",
    "주요 발견 및 기여": "ORD가 생성 품질과 분류 정확도를 동시에 향상; 모든 테스트 생성기와 호환",
    "한계": "k-폴드 CV 오버헤드 추가; 이진 불균형 특화; 임계값 τ 튜닝 필요",
    "출처": "AAAI 2025",
    "연도": 2025,
  },
  {
    "약어": "DBM",
    "제목": "긴 꼬리 인식을 위한 난이도 인식 균형 마진 손실",
    "코드": "github.com/quotation2520/dbm_ltr",
    "동기": "클래스 수준 재균형이 클래스 내 인스턴스 난이도를 무시; 어려운 샘플 처리 미흡",
    "목표": "이중 구성 마진 손실로 클래스 불균형과 인스턴스 난이도를 동시에 해결",
    "핵심 방법": "DBM 손실 = 클래스별 마진(클래스 빈도에 비례) + 인스턴스별 마진(어려운 양성 샘플의 클래스 중심까지 각도 거리)",
    "평가-데이터": "CIFAR-10/100-LT, ImageNet-LT, iNaturalist2018",
    "평가-비교 모델": "LDAM, BalancedSoftmax, BCL, MiSLAS, PaCo, LogitAdj",
    "평가-실험 내용": "LT 이미지 분류; 클래스별 vs. 인스턴스별 마진 절제; 기존 방법과 플러그인 실험",
    "지표": "정확도(많음/중간/적음), 전체 정확도",
    "주요 발견 및 기여": "DBM이 기존 LT 방법과 결합 시 일관되게 향상; 인스턴스별 마진이 어려운 양성 샘플에 핵심",
    "한계": "샘플당 각도 거리 계산 오버헤드; 두 마진 구성요소 튜닝 필요",
    "출처": "AAAI 2025",
    "연도": 2025,
  },
  {
    "약어": "BCE3S",
    "제목": "BCE3S: 긴 꼬리 인식을 위한 이진 교차 엔트로피 기반 삼자 시너지 학습",
    "코드": "github.com/wakinghours-github/BCE3S",
    "동기": "CE-Softmax가 불균형 분류기 벡터를 분모에서 결합해 불균형 증폭; BCE 기반 TSL 미개척",
    "목표": "공동 학습, 대조 학습, 균일 분류기 학습을 통합한 BCE 기반 삼자 시너지 학습 설계",
    "핵심 방법": "BCE3S = L_sc_bce(특징-분류기 BCE 공동 학습) + L_ss_bce(BCE 기반 대조 학습) + L_cc_bce(BCE 기반 균일 분류기 분리 가능성)",
    "평가-데이터": "CIFAR-10/100-LT, ImageNet-LT, iNaturalist2018",
    "평가-비교 모델": "CB Loss, RIDE, BCL, DisCo, ETF, RBL, NC-cRT",
    "평가-실험 내용": "다양한 IF에서 LT 분류; 각 BCE 구성요소 절제; 세 가지 TSL 모드 비교",
    "지표": "정확도(많음/중간/적음), 전체 정확도",
    "주요 발견 및 기여": "CIFAR-100-LT IF=100에서 SOTA 59.50%; BCE 균일 학습이 분류기 분리 가능성을 효과적으로 균형화",
    "한계": "BCE 훈련이 CE보다 복잡; 세 구성요소 손실 가중치 튜닝 필요",
    "출처": "AAAI 2026 (arXiv 2025년 11월)",
    "연도": 2026,
  },
]

# ── Excel helper ──────────────────────────────────────────────────────────────
HEADER_FILL  = PatternFill("solid", fgColor="2F4F8F")
HEADER_FONT  = Font(bold=True, color="FFFFFF", size=10)
ALT_FILL     = PatternFill("solid", fgColor="EEF2FF")
BORDER_SIDE  = Side(style="thin", color="BBBBBB")
CELL_BORDER  = Border(left=BORDER_SIDE, right=BORDER_SIDE,
                       top=BORDER_SIDE,  bottom=BORDER_SIDE)
WRAP         = Alignment(wrap_text=True, vertical="top")


def make_excel(records, out_path, columns):
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Paper Summary"

    # header
    for ci, col in enumerate(columns, 1):
        cell = ws.cell(row=1, column=ci, value=col)
        cell.fill   = HEADER_FILL
        cell.font   = HEADER_FONT
        cell.border = CELL_BORDER
        cell.alignment = Alignment(wrap_text=True, vertical="center",
                                   horizontal="center")

    ws.row_dimensions[1].height = 28

    for ri, rec in enumerate(records, 2):
        fill = ALT_FILL if ri % 2 == 0 else PatternFill()
        for ci, col in enumerate(columns, 1):
            val  = rec.get(col, "")
            cell = ws.cell(row=ri, column=ci, value=val)
            cell.fill      = fill
            cell.border    = CELL_BORDER
            cell.alignment = WRAP
            cell.font      = Font(size=9)
        ws.row_dimensions[ri].height = 72

    # column widths
    col_widths = {
        columns[0]:  10,   # Abb / 약어
        columns[1]:  35,   # Title / 제목
        columns[2]:  25,   # Codes / 코드
        columns[3]:  32,   # Motivation / 동기
        columns[4]:  32,   # Goal / 목표
        columns[5]:  38,   # Key methods / 핵심 방법
        columns[6]:  28,   # Eval-Data
        columns[7]:  30,   # Eval-Comparison Models
        columns[8]:  32,   # Eval-Experiments
        columns[9]:  22,   # Metrics / 지표
        columns[10]: 38,   # Key findings / 주요 발견
        columns[11]: 30,   # Limitations / 한계
        columns[12]: 18,   # Source / 출처
        columns[13]: 8,    # Year / 연도
    }
    for ci, col in enumerate(columns, 1):
        ws.column_dimensions[get_column_letter(ci)].width = col_widths.get(col, 20)

    ws.freeze_panes = "A2"
    wb.save(out_path)
    print(f"Saved: {out_path}")


EN_COLS = [
    "Abb.", "Title", "Codes",
    "Motivation", "Goal", "Key methods",
    "Eval-Data", "Eval-Comparison Models", "Eval-Experiments",
    "Metrics", "Key findings", "Limitations",
    "Source", "Year",
]

KO_COLS = [
    "약어", "제목", "코드",
    "동기", "목표", "핵심 방법",
    "평가-데이터", "평가-비교 모델", "평가-실험 내용",
    "지표", "주요 발견 및 기여", "한계",
    "출처", "연도",
]

make_excel(EN, "/home/user/Desktop/imbal_cic/reference/paper_summary_en.xlsx", EN_COLS)
make_excel(KO, "/home/user/Desktop/imbal_cic/reference/paper_summary_ko.xlsx", KO_COLS)
print("Done.")
