#!/usr/bin/env python3
"""
Add 20 new 2025-2026 imbalance papers to paper_summary_en.xlsx and paper_summary_ko.xlsx.
Also adds 'PDF Link' / 'PDF 링크' column to both files.
"""
import openpyxl
from openpyxl.styles import PatternFill, Font, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# ── Paper data (English) ─────────────────────────────────────────────────────
PAPERS_EN = [
    {
        "Abb.": "LOS",
        "Title": "Rethinking Classifier Re-Training in Long-Tailed Recognition: Label Over-Smooth Can Balance",
        "Codes": "https://github.com/Thinklab-SJTU/LOS",
        "Motivation": "Classifier re-training (Stage 2 of decoupled training) still fails on LT data because logit magnitudes vary wildly across classes; no diagnostic metric existed",
        "Goal": "Introduce Logits Magnitude (LoMa) metric to diagnose logit imbalance; propose Label Over-Smoothing (LOS) to prevent over-concentration of logits toward head classes",
        "Key methods": "Label Over-Smoothing: softens one-hot labels (true class slightly above 1/K, others slightly below); does not require class-frequency priors; plug-and-play into any decoupled framework",
        "Eval-Data": "CIFAR-100-LT, ImageNet-LT, iNaturalist 2018",
        "Eval-Comparison Models": "LA, cRT, MiSLAS, GCL, PaCo, BCL, RIDE",
        "Eval-Experiments": "Long-tailed multi-class image classification at multiple imbalance ratios; many/medium/few-shot split analysis",
        "Metrics": "Top-1 accuracy (overall, many, medium, few splits)",
        "Key findings": "LOS consistently outperforms all baselines on all three benchmarks; does not require knowledge of class frequencies at training time; compatible with existing Stage-1 methods",
        "Limitations": "Only addresses classifier re-training (Stage 2); does not improve representation quality from Stage 1",
        "Source": "ICLR 2025",
        "Year": 2025,
        "PDF Link": "https://openreview.net/pdf?id=OeKp3AdiVO",
    },
    {
        "Abb.": "ConMix",
        "Title": "ConMix: Contrastive Mixup at Representation Level for Long-tailed Deep Clustering",
        "Codes": "https://github.com/LZX-001/ConMix",
        "Motivation": "Deep clustering assumes balanced cluster distributions; real data is long-tailed but almost no prior work addresses long-tailed deep clustering",
        "Goal": "Design a contrastive clustering method that explicitly handles long-tailed class distributions without class-count labels",
        "Key methods": "Mixup at the representation level within a contrastive learning framework; theoretical proof that mixup-augmented contrastive objective re-balances gradient contributions across classes",
        "Eval-Data": "CIFAR-10-LT, CIFAR-100-LT, ImageNet-LT (multiple imbalance ratios)",
        "Eval-Comparison Models": "SCAN, SPICE, GCC and other deep clustering baselines",
        "Eval-Experiments": "Unsupervised clustering under long-tail distribution; evaluated across multiple IR values",
        "Metrics": "Accuracy (ACC), Normalized Mutual Information (NMI), Adjusted Rand Index (ARI)",
        "Key findings": "ConMix outperforms all state-of-the-art deep clustering methods across multiple imbalance ratios; representation-level mixup more effective than input-level mixup for clustering",
        "Limitations": "Evaluated primarily on visual data; real-world tabular or text clustering not explored",
        "Source": "ICLR 2025",
        "Year": 2025,
        "PDF Link": "https://openreview.net/pdf?id=3lH8WT0fhu",
    },
    {
        "Abb.": "LTRL",
        "Title": "LTRL: Boosting Long-Tail Recognition via Reflective Learning",
        "Codes": "https://github.com/fistyee/LTRL",
        "Motivation": "Long-tail recognition faces three intertwined problems: biased predictions on old samples, unrecognized cross-class feature relationships, and gradient conflicts between competing losses; prior work addresses each separately",
        "Goal": "Design a unified plug-and-play module that simultaneously corrects bias, enriches cross-class features, and harmonizes loss gradients",
        "Key methods": "Three lightweight modules: (1) reflection buffer reviewing past biased predictions; (2) cross-class feature relation summarization; (3) gradient conflict correction to harmonize multi-loss training",
        "Eval-Data": "CIFAR-10/100-LT (ResNet-32), ImageNet-LT (ResNeXt-50), Places-LT (ResNet-152), iNaturalist 2018 (ResNet-50)",
        "Eval-Comparison Models": "LDAM, BBN, MiSLAS, PaCo, GCL, TSC, SBCL",
        "Eval-Experiments": "Plug-in evaluation on top of existing LT methods; ablation of each module contribution",
        "Metrics": "Top-1 accuracy (overall, many, medium, few splits)",
        "Key findings": "LTRL consistently improves all plugged-in baselines; gradient conflict correction alone yields significant gains on tail classes",
        "Limitations": "Adds memory overhead for reflection buffer; evaluated only on standard vision benchmarks",
        "Source": "ECCV 2024",
        "Year": 2024,
        "PDF Link": "https://arxiv.org/pdf/2407.12568",
    },
    {
        "Abb.": "DaSC",
        "Title": "Distribution-Aware Robust Learning from Long-Tailed Data with Noisy Labels",
        "Codes": "https://github.com/JaesoonBaik1213/DaSC",
        "Motivation": "Real-world data is simultaneously long-tailed AND noisy; standard sample selection methods estimate class centroids from high-confidence samples and fail for tail classes that have too few clean examples",
        "Goal": "Jointly handle long-tail imbalance and label noise via distribution-aware centroid estimation and balanced contrastive learning",
        "Key methods": "Distribution-aware Class Centroid Estimation (DaCC): confidence-weighted centroid over all samples; Semi-supervised Balanced Contrastive Loss (SBCL) for clean samples; Mixup Instance Discrimination Loss (MIDL) for noisy samples",
        "Eval-Data": "CIFAR-10-LT + noise, CIFAR-100-LT + noise, mini-ImageNet-LT + noise (IR=100)",
        "Eval-Comparison Models": "DivideMix, Sel-CL, DISC, RoLT",
        "Eval-Experiments": "Simultaneous LT + noisy-label settings at varying noise rates and imbalance ratios",
        "Metrics": "Top-1 accuracy (overall, many/medium/few splits)",
        "Key findings": "DaCC-based centroid estimation significantly improves tail-class centroid quality; outperforms all LT+noisy baselines consistently",
        "Limitations": "Two-stage pipeline; requires clean validation set for threshold tuning",
        "Source": "ECCV 2024",
        "Year": 2024,
        "PDF Link": "https://arxiv.org/pdf/2407.16802",
    },
    {
        "Abb.": "RRB",
        "Title": "Rectify the Regression Bias in Long-Tailed Object Detection",
        "Codes": None,
        "Motivation": "LT detection research focused exclusively on classification bias; the regression branch also suffers from imbalance—head-class samples dominate regression training, causing poor localization on tail classes",
        "Goal": "Identify and correct regression-level bias in long-tailed object detection independently of classification-level bias correction",
        "Key methods": "Three complementary solutions: (1) class-agnostic regression branch training on all classes; (2) clustering regression heads for visually similar classes; (3) merged regression heads for rare classes sharing parameters across similar classes",
        "Eval-Data": "LVIS v1.0 (long-tailed instance segmentation and detection benchmark)",
        "Eval-Comparison Models": "Mask-RCNN, EQL, BAGS, SEESAW, LO-DET",
        "Eval-Experiments": "Long-tailed object detection and instance segmentation; analysis of regression vs. classification bias",
        "Metrics": "AP, AP_r (rare), AP_c (common), AP_f (frequent) on LVIS",
        "Key findings": "Regression bias is a distinct and significant source of tail-class degradation; combining regression and classification bias corrections yields additive improvement",
        "Limitations": "Extra inference overhead from class-agnostic branch; evaluated only on LVIS",
        "Source": "ECCV 2024",
        "Year": 2024,
        "PDF Link": "https://arxiv.org/pdf/2401.15885",
    },
    {
        "Abb.": "SIMBA",
        "Title": "Graph Size-imbalanced Learning with Energy-guided Structural Smoothing",
        "Codes": None,
        "Motivation": "Graph classification datasets follow power-law distributions of graph sizes; GNNs overfit large (head) graphs and underperform on small (tail) graphs, a problem distinct from class imbalance",
        "Goal": "Correct size-imbalanced learning in graph classification by energy-guided structural smoothing between head and tail graphs",
        "Key methods": "Graphs-to-Graph abstraction using inter-graph correlations; energy-based message-passing belief propagation re-weighting under-represented (small) graphs during training; structural feature smoothing across graph sizes",
        "Eval-Data": "REDDIT-B, IMDB-B, MUTAG, PROTEINS, COLLAB",
        "Eval-Comparison Models": "GK, WL, GIN, DIFFPOOL, SOLT-GNN",
        "Eval-Experiments": "Graph classification under size-imbalanced distributions; ablation of smoothing components",
        "Metrics": "Accuracy, Macro-F1",
        "Key findings": "SIMBA achieves 82.70% accuracy and 81.28% Macro-F1 on REDDIT-B vs. SOLT-GNN's 77.20%/80.43%; energy-guided smoothing effectively transfers head-graph information to size-tail graphs",
        "Limitations": "Graphs-to-Graph construction adds computational overhead; evaluated on small academic graph datasets",
        "Source": "WSDM 2025",
        "Year": 2025,
        "PDF Link": "https://arxiv.org/pdf/2412.17591",
    },
    {
        "Abb.": "AD-GSMOTE",
        "Title": "Adaptive Graph Enhancement for Imbalanced Multi-relation Graph Learning",
        "Codes": "https://github.com/graphprojects/AD-GSMOTE",
        "Motivation": "Multi-relation graphs suffer from class imbalance; existing graph oversampling methods ignore multi-relational structure and degree heterogeneity of minority-class nodes",
        "Goal": "Adapt SMOTE for multi-relation graphs by generating structurally valid and semantically meaningful minority synthetic nodes",
        "Key methods": "Degree-filtered minority node selection; adaptive center-node generator using correctly classified nodes; triadic edge generator for synthetic connectivity; semantic attention for multi-relation fusion; class-aware logit calibration at inference",
        "Eval-Data": "Twitter-Drug, YelpChi, Amazon",
        "Eval-Comparison Models": "GraphSMOTE, ImGAGN, GraphMixup, PC-GNN, RawlsGCN",
        "Eval-Experiments": "Node classification under class imbalance on multi-relation graphs; ablation of each component",
        "Metrics": "Macro-F1, AUC",
        "Key findings": "AD-GSMOTE achieves best Macro-F1 on all three datasets; adaptive center-node generation critical for synthetic quality",
        "Limitations": "Degree-filter heuristic may fail if minority classes are not degree-sparse; Twitter-Drug is a proprietary dataset",
        "Source": "WSDM 2025",
        "Year": 2025,
        "PDF Link": "https://dl.acm.org/doi/10.1145/3701551.3703553",
    },
    {
        "Abb.": "MATI",
        "Title": "Adapting to Evolving Data: Test-Time Expert Aggregation for Imbalanced Tabular Regression",
        "Codes": None,
        "Motivation": "Imbalanced regression on tabular data is worsened when test distributions shift over time; existing imbalanced regression methods fail under test-time distribution shift",
        "Goal": "Handle imbalanced tabular regression with test-time distribution shift via a mixture-of-experts approach requiring no retraining",
        "Key methods": "GMM-identified data sub-populations; specialized experts trained per region on synthetically augmented data; self-supervised test-time aggregation dynamically re-weights experts based on incoming test features",
        "Eval-Data": "House pricing, bike sharing, age prediction, and one additional tabular regression dataset",
        "Eval-Comparison Models": "SMOGN, ReSample, REBAGG, DIR",
        "Eval-Experiments": "Imbalanced tabular regression under distributional shift; comparison of static vs. adaptive expert aggregation",
        "Metrics": "MAE, RMSE (focus on rare-value prediction)",
        "Key findings": "MATI achieves 7.1% average MAE improvement over best baseline; gains are larger under distribution shift conditions",
        "Limitations": "Short paper (4 pages); GMM component count is a manual hyperparameter; no theoretical guarantee on adaptation quality",
        "Source": "WSDM 2026",
        "Year": 2026,
        "PDF Link": "https://arxiv.org/pdf/2506.07033",
    },
    {
        "Abb.": "GraphMuGu",
        "Title": "Generate or Re-Weight? A Mutual-Guidance Method for Class-Imbalanced Graphs",
        "Codes": None,
        "Motivation": "Node classification with class imbalance is addressed via generation or re-weighting in isolation; each strategy has blind spots the other can correct",
        "Goal": "Unify generative oversampling and sample re-weighting in a mutual-guidance framework where each branch informs the other",
        "Key methods": "Generative branch produces synthetic minority nodes guided by re-weighting branch confidence; re-weighting branch adjusts importance using generation quality signals; uncertainty-aware synthesis-quantity estimator; similarity-aware sample weighting",
        "Eval-Data": "Five class-imbalanced graph datasets (long-tailed and step-imbalance settings)",
        "Eval-Comparison Models": "GraphSMOTE, DPGNN, ImGAGN, GraphMixup, TAM, LTE4G",
        "Eval-Experiments": "Node classification under both long-tailed and step-imbalanced distributions",
        "Metrics": "Macro-F1, AUC",
        "Key findings": "GraphMuGu outperforms all baselines on both imbalance settings; mutual guidance significantly outperforms using either branch alone",
        "Limitations": "Joint training complexity; mutual guidance may be unstable if one branch diverges early",
        "Source": "IJCAI 2025",
        "Year": 2025,
        "PDF Link": "https://www.ijcai.org/proceedings/2025/0409.pdf",
    },
    {
        "Abb.": "DILDL",
        "Title": "Decoupled Imbalanced Label Distribution Learning",
        "Codes": None,
        "Motivation": "In Label Distribution Learning (LDL), dominant labels receive far higher description degrees than non-dominant labels, causing the model to ignore non-dominant label information during training",
        "Goal": "Decouple the label distribution into dominant and non-dominant components and independently balance their gradient contributions",
        "Key methods": "Decomposition of label distributions into dominant and non-dominant parts; separate Gaussian distribution alignment for each component; decoupled representation learning to independently calibrate imbalanced description degrees",
        "Eval-Data": "Standard LDL benchmarks (expression analysis, age estimation)",
        "Eval-Comparison Models": "SA-BFGS, LDLSF, LDLM, IncomLDL",
        "Eval-Experiments": "Multi-label soft distribution learning under dominant-label bias; ablation of decoupled components",
        "Metrics": "Clark distance, Chebyshev distance, Canberra metric, KL divergence",
        "Key findings": "DILDL outperforms all LDL baselines; decoupled treatment of dominant vs. non-dominant labels is key to the improvement",
        "Limitations": "Focused on soft label distribution scenarios; not directly applicable to hard multi-class classification",
        "Source": "IJCAI 2025",
        "Year": 2025,
        "PDF Link": "https://www.ijcai.org/proceedings/2025/0579.pdf",
    },
    {
        "Abb.": "LT-SpikeFormer",
        "Title": "Tackling Long-Tailed Data Challenges in Spiking Neural Networks via Heterogeneous Knowledge Distillation",
        "Codes": None,
        "Motivation": "Spiking Neural Networks are energy-efficient but completely unexplored for long-tailed recognition; binary spike representations make SNNs more vulnerable to class imbalance than ANNs",
        "Goal": "Enable long-tailed recognition in SNNs by transferring rich multi-scale representations from a pre-trained ANN teacher via heterogeneous knowledge distillation",
        "Key methods": "Transformer-based SNN architecture; heterogeneous knowledge distillation from ANN teacher; hierarchical cross-layer feature distillation transferring multi-scale representations to compensate for SNN's limited tail-class capacity",
        "Eval-Data": "CIFAR-10-LT, CIFAR-100-LT, ImageNet-LT (IR=10, 50, 100)",
        "Eval-Comparison Models": "BKD (SNN baseline), MDCS (self-distillation SNN), standard ANN LT methods",
        "Eval-Experiments": "Long-tailed recognition in SNN vs. ANN settings; analysis of spike-rate distribution across classes",
        "Metrics": "Top-1 accuracy (overall, many, medium, few splits)",
        "Key findings": "LT-SpikeFormer improves 5–10% over BKD (SNN baseline); heterogeneous distillation more effective than homogeneous SNN self-distillation",
        "Limitations": "Requires large ANN teacher at training time; real-world neuromorphic chip deployment not tested",
        "Source": "IJCAI 2025",
        "Year": 2025,
        "PDF Link": "https://www.ijcai.org/proceedings/2025/0157.pdf",
    },
    {
        "Abb.": "CFAMG",
        "Title": "Mitigating Data Imbalance in Time Series Classification Based on Counterfactual Minority Samples Augmentation",
        "Codes": None,
        "Motivation": "Temporal dependencies make naive oversampling (SMOTE) fail for imbalanced time series—it ignores temporal structure and generates unrealistic interpolations",
        "Goal": "Generate realistic counterfactual minority time-series samples via causal disentanglement to address class imbalance",
        "Key methods": "Disentangled encoder separating causal (class-determining) and non-causal (style) factors; counterfactual intervention replacing minority causal factors; mutual information constraints for disentanglement; minority class decoder for realistic synthesis",
        "Eval-Data": "53 constructed imbalanced datasets from UCR/UEA time-series benchmarks",
        "Eval-Comparison Models": "SMOTE, ADASYN, TimeGAN, TSMOTE and other temporal oversampling methods",
        "Eval-Experiments": "Imbalanced time-series classification across 53 datasets; classifier comparison (MLP, LSTM, ResNet)",
        "Metrics": "Macro-F1, AUC (focus on minority class performance)",
        "Key findings": "CFAMG improves 24.0%/18.6%/6.6% over best non-temporal method and 26.0%/22.2%/9.5% over best temporal method across three classifiers",
        "Limitations": "Causal factor disentanglement is approximate; sensitive to encoder architecture choice",
        "Source": "KDD 2025",
        "Year": 2025,
        "PDF Link": "https://dl.acm.org/doi/10.1145/3711896.3737049",
    },
    {
        "Abb.": "OVO-OVR",
        "Title": "Revisiting One-Versus-One and One-Versus-Rest: Insights into Imbalanced Multi-class Classification",
        "Codes": None,
        "Motivation": "OVO and OVR decomposition strategies are affected differently by class imbalance, but no systematic analysis exists; practitioners default to OVR without theoretical justification",
        "Goal": "Theoretically and empirically analyze when OVO vs. OVR is preferable under imbalanced multi-class settings; provide actionable guidelines",
        "Key methods": "Analytical conditions for OVO/OVR preference under varying imbalance ratios; theoretical bounds on error propagation under decomposition; empirical verification across classifiers and datasets",
        "Eval-Data": "Standard imbalanced multi-class benchmarks from UCI/LIBSVM",
        "Eval-Comparison Models": "SVM and gradient boosting under OVO vs. OVR decomposition",
        "Eval-Experiments": "Systematic comparison of OVO/OVR across classifiers, imbalance ratios, and number of classes",
        "Metrics": "Macro-F1, Balanced Accuracy, G-mean",
        "Key findings": "OVO consistently outperforms OVR under severe imbalance conditions; head classes in OVR negatively affect tail-class binary classifiers",
        "Limitations": "Primarily focused on linear/kernel classifiers; implications for deep neural networks remain unclear",
        "Source": "ICDM 2025",
        "Year": 2025,
        "PDF Link": "https://www3.cs.stonybrook.edu/~icdm2025/acceptedpapers.html",
    },
    {
        "Abb.": "Uni-GNN",
        "Title": "Overcoming Class Imbalance: Unified GNN Learning with Structural and Semantic Connectivity Representations",
        "Codes": None,
        "Motivation": "Class-imbalanced node classification is exacerbated by GNNs' reliance on 1-hop neighborhood aggregation, which limits information diffusion for isolated minority-class nodes",
        "Goal": "Unify structural and semantic connectivity in GNNs with balanced pseudo-label generation to leverage unlabeled nodes for minority class augmentation",
        "Key methods": "Dual structural+semantic connectivity representation; information diffusion beyond 1-hop neighbors for minority-class nodes; balanced pseudo-label generation from unlabeled nodes; joint self-training objective",
        "Eval-Data": "Standard node classification benchmarks (Cora, Citeseer, Amazon) with induced class imbalance",
        "Eval-Comparison Models": "GraphSMOTE, DPGNN, ImGAGN, TAM, LTE4G",
        "Eval-Experiments": "Node classification under class imbalance; analysis of 1-hop vs. extended connectivity",
        "Metrics": "Macro-F1, AUC",
        "Key findings": "Extending connectivity beyond 1-hop significantly benefits minority-class nodes; unified structural+semantic representation outperforms each modality alone",
        "Limitations": "Pseudo-label quality degrades under severe imbalance; extended connectivity increases computational cost",
        "Source": "NeurIPS 2025",
        "Year": 2025,
        "PDF Link": "https://neurips.cc/virtual/2025/poster/127625",
    },
    {
        "Abb.": "IP-DPP",
        "Title": "Long-Tailed Recognition via Information-Preservable Two-Stage Learning",
        "Codes": "https://github.com/fudong03/BNS_IPDPP",
        "Motivation": "Two-stage decoupled training can lose valuable tail-class information in Stage 2 by naive balanced sampling, which discards head-class data",
        "Goal": "Rectify majority bias in classifier re-training while preserving maximum information from all classes including head classes",
        "Key methods": "Stage 1: Balanced Neighborhood Sampling (BNS) minimizing intra-class feature distance; Stage 2: Information-Preservable Determinantal Point Process (IP-DPP) selecting maximally diverse, informative data subsets that naturally balance classes",
        "Eval-Data": "CIFAR-10-LT, CIFAR-100-LT, ImageNet-LT, iNaturalist 2018",
        "Eval-Comparison Models": "KCL, TSC, SBCL, MiSLAS, BCL",
        "Eval-Experiments": "Two-stage LT recognition; ablation of BNS and IP-DPP contributions; comparison of sampling strategies",
        "Metrics": "Top-1 accuracy (overall, many, medium, few splits)",
        "Key findings": "IP-DPP achieves state-of-the-art across all benchmarks; preserving head-class diversity in Stage 2 is critical for overall accuracy",
        "Limitations": "DPP inference has cubic complexity in set size; approximation methods needed for large datasets",
        "Source": "NeurIPS 2025",
        "Year": 2025,
        "PDF Link": "https://arxiv.org/pdf/2510.08836",
    },
    {
        "Abb.": "IBCL",
        "Title": "Improved Balanced Classification with Theoretically Grounded Loss Functions",
        "Codes": None,
        "Motivation": "Logit-Adjusted (LA) and class-weighted losses are dominant but lack strong theoretical backing; H-consistency bounds are needed to identify theoretically sound loss families",
        "Goal": "Derive H-consistency bounds for balanced classification losses and propose improved loss families (GLA and GCA) with stronger theoretical guarantees",
        "Key methods": "Generalized Logit-Adjusted (GLA) losses extending LA to full cross-entropy family; Generalized Class-Aware weighted (GCA) losses with class-dependent confidence margins; GCA achieves H-consistency bound scaling as 1/√p_min under severe imbalance",
        "Eval-Data": "CIFAR-LT, ImageNet-LT (standard imbalanced classification benchmarks)",
        "Eval-Comparison Models": "Standard CE, LA loss, class-weighted CE",
        "Eval-Experiments": "Balanced multi-class classification under varying imbalance ratios; theoretical analysis of bounds",
        "Metrics": "Balanced accuracy, Macro-F1",
        "Key findings": "GCA achieves the strongest theoretical guarantees under severe imbalance (1/√p_min scaling); GLA outperforms LA on common benchmarks",
        "Limitations": "Empirical gains over LA are modest; theoretical results assume specific hypothesis class conditions",
        "Source": "NeurIPS 2025",
        "Year": 2025,
        "PDF Link": "https://arxiv.org/pdf/2512.23947",
    },
    {
        "Abb.": "OSB-SMOTE",
        "Title": "Concentration and excess risk bounds for imbalanced classification with synthetic oversampling",
        "Codes": None,
        "Motivation": "SMOTE is widely used for imbalanced classification but lacks theoretical justification; no concentration or excess risk guarantees exist for classifiers trained on SMOTE-generated data",
        "Goal": "Provide the first rigorous theoretical framework for SMOTE including concentration bounds, excess risk guarantees, and parameter guidance",
        "Key methods": "Uniform concentration bound on empirical risk over synthetic minority samples; nonparametric excess risk guarantee for kernel classifiers trained with synthetic oversampling; optimal parameter guidance for k-neighbors and mixing coefficients",
        "Eval-Data": "Standard imbalanced classification datasets (theoretical validation)",
        "Eval-Comparison Models": "Naive oversampling, no oversampling",
        "Eval-Experiments": "Theoretical derivation with empirical validation on standard imbalanced datasets",
        "Metrics": "AUC, Balanced accuracy (empirical); concentration and excess risk bounds (theoretical)",
        "Key findings": "First concentration and excess risk bounds for SMOTE; optimal SMOTE parameter regime identified; kernel classifier trained on SMOTE data converges at optimal nonparametric rate",
        "Limitations": "Results restricted to kernel classifiers; neural network extensions remain open",
        "Source": "NeurIPS 2025",
        "Year": 2025,
        "PDF Link": "https://arxiv.org/pdf/2510.20472",
    },
    {
        "Abb.": "ImGDA",
        "Title": "Dual Prototype-Enhanced Contrastive Framework for Class-Imbalanced Graph Domain Adaptation",
        "Codes": "https://github.com/maxin88scu/ImGDA",
        "Motivation": "Graph domain adaptation fails when source domain has class imbalance—standard alignment incorrectly aligns rare source classes to head target classes",
        "Goal": "Correct source-domain class imbalance during cross-graph domain adaptation via dual-prototype contrastive learning",
        "Key methods": "Dual-branch graph encoder (local + global) generating class-specific prototypes; cross-branch contrastive learning within source domain to mitigate imbalance; cross-domain contrast with pseudo-labels to align semantically similar cross-domain pairs",
        "Eval-Data": "Standard graph domain adaptation benchmarks (Citation network variants)",
        "Eval-Comparison Models": "DANN, CDAN, UDAGCN, JHGDA and other graph domain adaptation methods",
        "Eval-Experiments": "Unsupervised graph domain adaptation under class-imbalanced source domains; ablation of local vs. global prototype contributions",
        "Metrics": "Macro-F1, Node classification accuracy",
        "Key findings": "ImGDA outperforms all graph domain adaptation baselines; dual-branch prototype generation critical for cross-domain class alignment",
        "Limitations": "Requires selecting anchor prototypes (sensitive to anchor quality); limited to unsupervised target settings",
        "Source": "NeurIPS 2025",
        "Year": 2025,
        "PDF Link": "https://openreview.net/pdf?id=QSK8VqiijI",
    },
    {
        "Abb.": "RLAL",
        "Title": "Revisiting Long-Tailed Learning: Insights from an Architectural Perspective",
        "Codes": None,
        "Motivation": "All existing LT methods treat network architecture as fixed and only modify training procedures; the architecture itself may introduce imbalance bias",
        "Goal": "Analyze how topology, convolution type, and activations affect LT performance; design LT-aware architectures via Neural Architecture Search",
        "Key methods": "LT-AggConv and LT-HierConv novel operations for LT robustness; LT-DARTS NAS with long-tail-aware search space and unbiased search strategy; discovered architectures combinable with existing loss/sampling methods",
        "Eval-Data": "CIFAR-10-LT, CIFAR-100-LT, ImageNet-LT",
        "Eval-Comparison Models": "Standard ResNet, ResNeXt; LA loss, MiSLAS as combined baselines",
        "Eval-Experiments": "Architecture search for LT; ablation of LT-AggConv/LT-HierConv; combination with existing LT training methods",
        "Metrics": "Top-1 accuracy (overall, many, medium, few splits)",
        "Key findings": "Architectural design is an independent and additive source of LT improvement; LT-DARTS architectures stack with method-level gains",
        "Limitations": "NAS search is computationally expensive; discovered architectures may not generalize across all imbalance ratios",
        "Source": "CIKM 2025",
        "Year": 2025,
        "PDF Link": "https://arxiv.org/pdf/2411.06098",
    },
    {
        "Abb.": "GraphIAM",
        "Title": "GraphIAM: Two-Stage Algorithm for Improving Class-Imbalanced Node Classification on Attribute-Missing Graphs",
        "Codes": None,
        "Motivation": "Node classification on attribute-missing graphs is doubly hard: missing attributes degrade feature quality, and class imbalance biases training toward majority classes; minority nodes tend to be both attribute-sparse and degree-sparse",
        "Goal": "Handle simultaneous attribute incompleteness and class imbalance in node classification via a two-stage algorithm",
        "Key methods": "Stage 1: attribute imputation using neighborhood aggregation and semantic propagation; Stage 2: imbalance-aware node classification on the completed graph; stages mutually informed to prevent error propagation",
        "Eval-Data": "Cora, Citeseer, and other node classification datasets with induced attribute-missing and class-imbalance conditions",
        "Eval-Comparison Models": "GraphSMOTE, DPGNN, TAM and attribute-imputation baselines",
        "Eval-Experiments": "Node classification under combined attribute-missing and class-imbalanced conditions",
        "Metrics": "Macro-F1, AUC",
        "Key findings": "GraphIAM outperforms all baselines; joint consideration of attribute-missingness and imbalance is more effective than addressing each separately",
        "Limitations": "Two-stage pipeline: if Stage 1 imputation is poor, Stage 2 cannot recover; evaluated primarily on citation networks",
        "Source": "CIKM 2025",
        "Year": 2025,
        "PDF Link": "https://www.cikm2025.org/program/accepted-papers",
    },
]

# ── Korean translation ────────────────────────────────────────────────────────
PAPERS_KO = [
    {
        "약어": "LOS",
        "제목": "불균형 인식에서 분류기 재훈련 재고찰: 레이블 과-평활화가 균형을 이룰 수 있다",
        "코드": "https://github.com/Thinklab-SJTU/LOS",
        "동기": "2단계 분리 훈련의 분류기 재훈련이 클래스 간 로짓 크기 편차로 인해 여전히 LT 데이터에서 실패함; 진단 지표가 없었음",
        "목표": "로짓 불균형 진단을 위한 LoMa 지표 도입; 헤드 클래스 쪽으로 로짓이 과집중되는 것을 방지하는 LOS 제안",
        "핵심 방법": "레이블 과-평활화: 원-핫 레이블을 완화(진짜 클래스 ≈ 1/K+ε); 클래스 빈도 정보 불필요; 분리 훈련 프레임워크에 플러그인 가능",
        "평가-데이터": "CIFAR-100-LT, ImageNet-LT, iNaturalist 2018",
        "평가-비교 모델": "LA, cRT, MiSLAS, GCL, PaCo, BCL, RIDE",
        "평가-실험 내용": "다양한 IR에서 LT 다중 클래스 이미지 분류; many/medium/few-shot 분할 분석",
        "지표": "Top-1 정확도 (전체, many/medium/few 분할)",
        "주요 발견 및 기여": "LOS는 세 벤치마크 모두에서 모든 기준선을 일관되게 초과; 클래스 빈도 정보 불필요; 기존 Stage-1 방법과 호환",
        "한계": "Stage 2 분류기 재훈련에만 적용; Stage 1 표현 품질 개선 없음",
        "출처": "ICLR 2025",
        "연도": 2025,
        "PDF 링크": "https://openreview.net/pdf?id=OeKp3AdiVO",
    },
    {
        "약어": "ConMix",
        "제목": "ConMix: 긴 꼬리 심층 클러스터링을 위한 표현 수준 대조적 믹스업",
        "코드": "https://github.com/LZX-001/ConMix",
        "동기": "심층 클러스터링은 균형 분포를 가정하지만 실제 데이터는 긴 꼬리를 따름; 긴 꼬리 심층 클러스터링을 다룬 연구가 거의 없음",
        "목표": "클래스 수 레이블 없이 긴 꼬리 클래스 분포를 명시적으로 처리하는 대조적 클러스터링 방법 설계",
        "핵심 방법": "대조 학습 프레임워크 내 표현 수준 믹스업; 믹스업 증강 대조 목적이 클래스 간 경사도 기여를 재균형함을 이론적 증명",
        "평가-데이터": "CIFAR-10-LT, CIFAR-100-LT, ImageNet-LT (다중 IR)",
        "평가-비교 모델": "SCAN, SPICE, GCC 등 심층 클러스터링 기준선",
        "평가-실험 내용": "긴 꼬리 분포 하에서의 비지도 클러스터링; 다중 IR 값 평가",
        "지표": "정확도(ACC), 정규화 상호 정보(NMI), 조정 랜드 지수(ARI)",
        "주요 발견 및 기여": "ConMix는 다중 IR에서 모든 최신 심층 클러스터링 방법을 초과; 표현 수준 믹스업이 입력 수준보다 효과적",
        "한계": "주로 시각 데이터에서 평가; 테이블형/텍스트 클러스터링에 대한 탐구 없음",
        "출처": "ICLR 2025",
        "연도": 2025,
        "PDF 링크": "https://openreview.net/pdf?id=3lH8WT0fhu",
    },
    {
        "약어": "LTRL",
        "제목": "LTRL: 반성적 학습을 통한 긴 꼬리 인식 향상",
        "코드": "https://github.com/fistyee/LTRL",
        "동기": "LT 인식은 편향된 예측, 클래스 간 특징 관계 미활용, 다중 손실 간 경사도 충돌이라는 세 가지 문제를 동시에 가지며 각 문제가 독립적으로만 다루어져 왔음",
        "목표": "편향 교정, 클래스 간 특징 풍부화, 손실 경사도 조화를 동시에 수행하는 플러그인 모듈 설계",
        "핵심 방법": "세 경량 모듈: (1) 과거 편향 예측 검토 반성 버퍼; (2) 클래스 간 특징 관계 요약; (3) 다중 손실 훈련 조화를 위한 경사도 충돌 교정",
        "평가-데이터": "CIFAR-10/100-LT (ResNet-32), ImageNet-LT (ResNeXt-50), Places-LT (ResNet-152), iNaturalist 2018 (ResNet-50)",
        "평가-비교 모델": "LDAM, BBN, MiSLAS, PaCo, GCL, TSC, SBCL",
        "평가-실험 내용": "기존 LT 방법에 플러그인 평가; 각 모듈 기여도 절제 실험",
        "지표": "Top-1 정확도 (전체, many/medium/few 분할)",
        "주요 발견 및 기여": "LTRL은 플러그인된 모든 기준선을 일관되게 향상; 경사도 충돌 교정만으로도 테일 클래스에서 유의미한 향상",
        "한계": "반성 버퍼로 인한 메모리 오버헤드; 표준 시각 벤치마크에서만 평가",
        "출처": "ECCV 2024",
        "연도": 2024,
        "PDF 링크": "https://arxiv.org/pdf/2407.12568",
    },
    {
        "약어": "DaSC",
        "제목": "긴 꼬리 데이터와 잡음 레이블로부터의 분포 인식 강건 학습",
        "코드": "https://github.com/JaesoonBaik1213/DaSC",
        "동기": "실제 데이터는 긴 꼬리이면서 동시에 잡음을 포함함; 표준 샘플 선택은 테일 클래스 중심점 추정에 실패 (깨끗한 샘플 부족)",
        "목표": "분포 인식 중심점 추정과 균형 대조 학습으로 LT와 잡음 레이블을 동시에 처리",
        "핵심 방법": "DaCC (신뢰도 가중 중심점); 고신뢰 샘플에 SBCL; 저신뢰 샘플에 믹스업 인스턴스 판별 손실(MIDL)",
        "평가-데이터": "CIFAR-10/100-LT + 잡음, mini-ImageNet-LT + 잡음 (IR=100)",
        "평가-비교 모델": "DivideMix, Sel-CL, DISC, RoLT",
        "평가-실험 내용": "다양한 잡음율과 IR에서 LT+잡음 레이블 동시 설정 평가",
        "지표": "Top-1 정확도 (전체, many/medium/few 분할)",
        "주요 발견 및 기여": "DaCC 기반 중심점 추정이 테일 클래스 품질을 크게 향상; 모든 LT+잡음 기준선 초과",
        "한계": "2단계 파이프라인; 임계값 조정에 깨끗한 검증 세트 필요",
        "출처": "ECCV 2024",
        "연도": 2024,
        "PDF 링크": "https://arxiv.org/pdf/2407.16802",
    },
    {
        "약어": "RRB",
        "제목": "긴 꼬리 객체 탐지에서 회귀 편향 교정",
        "코드": None,
        "동기": "LT 탐지 연구는 분류 편향에만 집중했으나, 회귀 분기도 불균형으로 인해 편향됨—헤드 클래스가 회귀 훈련을 지배하여 테일 클래스의 위치 지정이 열악해짐",
        "목표": "분류 편향과 독립적으로 긴 꼬리 객체 탐지에서 회귀 수준 편향을 식별하고 교정",
        "핵심 방법": "세 가지 보완 해법: (1) 전체 클래스에 훈련되는 클래스 비인식 회귀 분기; (2) 시각적으로 유사한 클래스를 위한 회귀 헤드 클러스터링; (3) 희귀 클래스를 위한 유사 클래스 간 파라미터 공유 회귀 헤드 병합",
        "평가-데이터": "LVIS v1.0 (긴 꼬리 인스턴스 분할 및 탐지 벤치마크)",
        "평가-비교 모델": "Mask-RCNN, EQL, BAGS, SEESAW, LO-DET",
        "평가-실험 내용": "긴 꼬리 객체 탐지 및 인스턴스 분할; 회귀 vs. 분류 편향 분석",
        "지표": "AP, AP_r (희귀), AP_c (일반), AP_f (빈번) on LVIS",
        "주요 발견 및 기여": "회귀 편향은 테일 클래스 성능 저하의 별도의 중요한 원인; 회귀와 분류 편향 교정의 결합이 가산적 향상을 가져옴",
        "한계": "클래스 비인식 분기로 인한 추론 오버헤드; LVIS에서만 평가",
        "출처": "ECCV 2024",
        "연도": 2024,
        "PDF 링크": "https://arxiv.org/pdf/2401.15885",
    },
    {
        "약어": "SIMBA",
        "제목": "에너지 안내 구조적 평활화를 통한 그래프 크기 불균형 학습",
        "코드": None,
        "동기": "그래프 분류 데이터셋은 그래프 크기의 멱법칙 분포를 따름; GNN이 큰 그래프(헤드)에 과적합하여 작은 그래프(테일)에서 성능 저하",
        "목표": "에너지 안내 구조적 평활화로 그래프 분류에서 크기 불균형 학습을 교정",
        "핵심 방법": "그래프 간 상관관계를 이용한 Graphs-to-Graph 추상화; 에너지 기반 메시지 전달 믿음 전파로 작은 그래프 재가중; 그래프 크기 간 구조적 특징 평활화",
        "평가-데이터": "REDDIT-B, IMDB-B, MUTAG, PROTEINS, COLLAB",
        "평가-비교 모델": "GK, WL, GIN, DIFFPOOL, SOLT-GNN",
        "평가-실험 내용": "크기 불균형 분포 하에서 그래프 분류; 평활화 구성 요소 절제",
        "지표": "정확도, Macro-F1",
        "주요 발견 및 기여": "SIMBA는 REDDIT-B에서 정확도 82.70%, Macro-F1 81.28% 달성 (SOLT-GNN 대비 77.20%/80.43%); 에너지 안내 평활화가 헤드-그래프 정보를 테일 그래프에 효과적으로 전달",
        "한계": "Graphs-to-Graph 구성에 추가 계산 비용; 소규모 학술 그래프에서만 평가",
        "출처": "WSDM 2025",
        "연도": 2025,
        "PDF 링크": "https://arxiv.org/pdf/2412.17591",
    },
    {
        "약어": "AD-GSMOTE",
        "제목": "불균형 다중 관계 그래프 학습을 위한 적응적 그래프 향상",
        "코드": "https://github.com/graphprojects/AD-GSMOTE",
        "동기": "다중 관계 그래프는 클래스 불균형을 겪음; 기존 그래프 오버샘플링은 다중 관계 구조와 소수 클래스 노드의 차수 이질성을 무시",
        "목표": "다중 관계 그래프를 위해 구조적으로 유효하고 의미론적으로 의미 있는 소수 합성 노드를 생성하도록 SMOTE를 적응",
        "핵심 방법": "차수 필터링 소수 노드 선택; 이전 에포크 정확 분류 노드 기반 적응적 중심 노드 생성기; 삼각 엣지 생성기; 다중 관계 유형 간 의미론적 어텐션 융합; 클래스 인식 로짓 보정",
        "평가-데이터": "Twitter-Drug, YelpChi, Amazon",
        "평가-비교 모델": "GraphSMOTE, ImGAGN, GraphMixup, PC-GNN, RawlsGCN",
        "평가-실험 내용": "다중 관계 그래프에서 클래스 불균형 하 노드 분류; 각 구성요소 절제",
        "지표": "Macro-F1, AUC",
        "주요 발견 및 기여": "AD-GSMOTE는 세 데이터셋 모두에서 최고 Macro-F1 달성; 적응적 중심 노드 생성이 합성 품질에 핵심적",
        "한계": "소수 클래스가 차수-희소하지 않으면 차수 필터 발견법이 실패할 수 있음; Twitter-Drug는 독점 데이터셋",
        "출처": "WSDM 2025",
        "연도": 2025,
        "PDF 링크": "https://dl.acm.org/doi/10.1145/3701551.3703553",
    },
    {
        "약어": "MATI",
        "제목": "진화하는 데이터에 적응: 불균형 테이블형 회귀를 위한 테스트 시간 전문가 집계",
        "코드": None,
        "동기": "테이블형 데이터의 불균형 회귀는 테스트 분포가 시간에 따라 변화할 때 악화; 기존 불균형 회귀 방법은 테스트 시간 분포 이동 처리 불가",
        "목표": "재훈련 없이 테스트 시간 분포 이동에서 불균형 테이블형 회귀를 혼합 전문가 방식으로 처리",
        "핵심 방법": "GMM으로 데이터 하위 집단 식별; 합성 증강 데이터로 영역별 전문가 훈련; 테스트 시간 자기지도 집계로 입력 특징 기반 전문가 동적 가중",
        "평가-데이터": "주택 가격, 자전거 공유, 나이 예측 등 테이블형 회귀 데이터셋",
        "평가-비교 모델": "SMOGN, ReSample, REBAGG, DIR",
        "평가-실험 내용": "분포 이동 하에서 불균형 테이블형 회귀; 정적 vs. 적응적 전문가 집계 비교",
        "지표": "MAE, RMSE (희귀값 예측 중점)",
        "주요 발견 및 기여": "MATI는 최고 기준선 대비 평균 MAE 7.1% 향상; 분포 이동 조건에서 더 큰 향상",
        "한계": "단문(4쪽); GMM 구성 요소 수 수동 초매개변수; 적응 품질에 대한 이론적 보장 없음",
        "출처": "WSDM 2026",
        "연도": 2026,
        "PDF 링크": "https://arxiv.org/pdf/2506.07033",
    },
    {
        "약어": "GraphMuGu",
        "제목": "생성 또는 재가중? 클래스 불균형 그래프를 위한 상호 안내 방법",
        "코드": None,
        "동기": "그래프 클래스 불균형 노드 분류는 생성(오버샘플링) 또는 재가중으로 독립 처리되어 왔으나 각 전략에 맹점이 존재",
        "목표": "생성 오버샘플링과 샘플 재가중을 상호 안내하는 통합 프레임워크 구축",
        "핵심 방법": "재가중 분기 신뢰도로 안내받는 생성 분기; 생성 품질 신호로 가중치 조정하는 재가중 분기; 불확실성 인식 합성량 추정기; 유사도 인식 샘플 가중치 모듈",
        "평가-데이터": "5개 클래스 불균형 그래프 데이터셋 (긴 꼬리 및 계단형 불균형)",
        "평가-비교 모델": "GraphSMOTE, DPGNN, ImGAGN, GraphMixup, TAM, LTE4G",
        "평가-실험 내용": "긴 꼬리와 계단형 불균형 모두에서 노드 분류",
        "지표": "Macro-F1, AUC",
        "주요 발견 및 기여": "GraphMuGu는 두 불균형 설정 모두에서 모든 기준선 초과; 상호 안내가 각 분기만 사용할 때보다 크게 우수",
        "한계": "공동 훈련 복잡성 증가; 한 분기가 초기에 발산하면 상호 안내가 불안정해질 수 있음",
        "출처": "IJCAI 2025",
        "연도": 2025,
        "PDF 링크": "https://www.ijcai.org/proceedings/2025/0409.pdf",
    },
    {
        "약어": "DILDL",
        "제목": "분리된 불균형 레이블 분포 학습",
        "코드": None,
        "동기": "레이블 분포 학습에서 지배적 레이블이 비지배적 레이블보다 훨씬 높은 기술 정도를 받아 모델이 비지배적 레이블 정보를 무시하게 됨",
        "목표": "레이블 분포를 지배적/비지배적 구성 요소로 분해하고 각각의 경사도 기여를 독립적으로 균형화",
        "핵심 방법": "지배적/비지배적 레이블 분포 분해; 각 구성요소에 대한 분리된 가우시안 분포 정렬; 불균형 기술 정도를 독립적으로 보정하는 분리 표현 학습",
        "평가-데이터": "표준 LDL 벤치마크 (표정 분석, 나이 추정)",
        "평가-비교 모델": "SA-BFGS, LDLSF, LDLM, IncomLDL",
        "평가-실험 내용": "지배적 레이블 편향 하에서 다중 레이블 소프트 분포 학습; 분리 구성요소 절제",
        "지표": "Clark 거리, Chebyshev 거리, Canberra 지표, KL 발산",
        "주요 발견 및 기여": "DILDL은 모든 LDL 기준선을 초과; 지배적/비지배적 레이블 분리 처리가 핵심",
        "한계": "소프트 레이블 분포 시나리오에 한정; 하드 다중 클래스 분류에 직접 적용 불가",
        "출처": "IJCAI 2025",
        "연도": 2025,
        "PDF 링크": "https://www.ijcai.org/proceedings/2025/0579.pdf",
    },
    {
        "약어": "LT-SpikeFormer",
        "제목": "이질적 지식 증류를 통한 스파이킹 신경망의 긴 꼬리 데이터 과제 해결",
        "코드": None,
        "동기": "스파이킹 신경망(SNN)은 에너지 효율적이지만 긴 꼬리 인식에 전혀 탐구되지 않았음; 이진 스파이크 표현이 SNN을 클래스 불균형에 더 취약하게 만듦",
        "목표": "사전 훈련된 ANN 교사로부터 이질적 지식 증류를 통해 SNN에서 긴 꼬리 인식 활성화",
        "핵심 방법": "트랜스포머 기반 SNN; ANN 교사로부터 이질적 지식 증류; 계층적 교차 레이어 특징 증류로 SNN의 테일 클래스 제한적 표현 용량 보상",
        "평가-데이터": "CIFAR-10-LT, CIFAR-100-LT, ImageNet-LT (IR=10, 50, 100)",
        "평가-비교 모델": "BKD (SNN 기준선), MDCS (자기증류 SNN), 표준 ANN LT 방법",
        "평가-실험 내용": "SNN vs. ANN 설정에서 긴 꼬리 인식; 클래스 간 스파이크율 분포 분석",
        "지표": "Top-1 정확도 (전체, many/medium/few 분할)",
        "주요 발견 및 기여": "BKD (SNN 기준선) 대비 5~10% 향상; 이질적 증류가 동질적 SNN 자기증류보다 효과적",
        "한계": "훈련 시 대형 ANN 교사 필요; 실제 뉴로모픽 칩 배포 미검증",
        "출처": "IJCAI 2025",
        "연도": 2025,
        "PDF 링크": "https://www.ijcai.org/proceedings/2025/0157.pdf",
    },
    {
        "약어": "CFAMG",
        "제목": "반사실적 소수 샘플 증강 기반 시계열 분류에서 데이터 불균형 완화",
        "코드": None,
        "동기": "시간적 의존성으로 인해 단순 오버샘플링(SMOTE)이 불균형 시계열에서 실패—시간 구조를 무시하고 비현실적인 보간을 생성",
        "목표": "인과적 분리를 통한 반사실적 소수 시계열 샘플 생성으로 클래스 불균형 해결",
        "핵심 방법": "인과적(클래스 결정)·비인과적(스타일) 요소를 분리하는 인코더; 소수 인과 요소를 이용한 반사실적 개입; 분리를 강제하는 상호 정보 제약; 소수 클래스 디코더",
        "평가-데이터": "UCR/UEA 시계열 벤치마크에서 구성된 53개 불균형 데이터셋",
        "평가-비교 모델": "SMOTE, ADASYN, TimeGAN, TSMOTE 등 시간적 오버샘플링 방법",
        "평가-실험 내용": "53개 데이터셋에서 불균형 시계열 분류; 분류기 비교 (MLP, LSTM, ResNet)",
        "지표": "Macro-F1, AUC (소수 클래스 성능 중점)",
        "주요 발견 및 기여": "세 분류기에서 최고 비시간적 방법 대비 24%/18.6%/6.6%, 최고 시간적 방법 대비 26%/22.2%/9.5% 향상",
        "한계": "인과 요소 분리가 근사적; 인코더 아키텍처 선택에 민감",
        "출처": "KDD 2025",
        "연도": 2025,
        "PDF 링크": "https://dl.acm.org/doi/10.1145/3711896.3737049",
    },
    {
        "약어": "OVO-OVR",
        "제목": "1대1 vs 1대나머지 재고찰: 불균형 다중 클래스 분류 통찰",
        "코드": None,
        "동기": "OVO와 OVR 분해 전략은 클래스 불균형에 다르게 영향받지만 체계적 분석이 없음; 실무자들이 이론적 근거 없이 OVR 기본값을 사용",
        "목표": "불균형 다중 클래스 설정에서 OVO vs. OVR 선호 조건을 이론적·실험적으로 분석; 실용적 가이드라인 제공",
        "핵심 방법": "다양한 IR에서 OVO/OVR 선호에 대한 분석적 조건 도출; 분해 하에서 오류 전파 이론적 경계; 분류기와 데이터셋 전반 실증 검증",
        "평가-데이터": "UCI/LIBSVM 표준 불균형 다중 클래스 벤치마크",
        "평가-비교 모델": "OVO/OVR 분해 하에서 SVM 및 경사 부스팅",
        "평가-실험 내용": "분류기, IR, 클래스 수에 걸친 OVO/OVR 체계적 비교",
        "지표": "Macro-F1, 균형 정확도, G-mean",
        "주요 발견 및 기여": "심각한 불균형 조건에서 OVO가 일관되게 OVR을 초과; OVR에서 헤드 클래스가 테일 클래스 이진 분류기에 부정적 영향",
        "한계": "주로 선형/커널 분류기에 집중; 심층 신경망에 대한 함의 불분명",
        "출처": "ICDM 2025",
        "연도": 2025,
        "PDF 링크": "https://www3.cs.stonybrook.edu/~icdm2025/acceptedpapers.html",
    },
    {
        "약어": "Uni-GNN",
        "제목": "클래스 불균형 극복: 구조적 및 의미론적 연결 표현을 통한 통합 GNN 학습",
        "코드": None,
        "동기": "클래스 불균형 노드 분류는 GNN의 1-홉 이웃 집계 의존성으로 악화; 고립된 소수 클래스 노드의 정보 확산이 제한됨",
        "목표": "구조적·의미론적 연결성을 통합하고 균형 의사 레이블 생성으로 미레이블 노드를 소수 클래스 증강에 활용",
        "핵심 방법": "이중 구조적+의미론적 연결 표현; 소수 클래스 노드의 1-홉 이상 정보 확산; 미레이블 노드로부터 균형 의사 레이블 생성; 공동 자기훈련 목적함수",
        "평가-데이터": "Cora, Citeseer, Amazon 등 노드 분류 벤치마크 (유도 클래스 불균형)",
        "평가-비교 모델": "GraphSMOTE, DPGNN, ImGAGN, TAM, LTE4G",
        "평가-실험 내용": "클래스 불균형 하 노드 분류; 1-홉 vs. 확장 연결성 분석",
        "지표": "Macro-F1, AUC",
        "주요 발견 및 기여": "1-홉 이상 연결성 확장이 소수 클래스 노드에 크게 유익; 구조적+의미론적 통합 표현이 각 모달리티 단독보다 우수",
        "한계": "심각한 불균형 하에서 의사 레이블 품질 저하; 확장 연결성으로 계산 비용 증가",
        "출처": "NeurIPS 2025",
        "연도": 2025,
        "PDF 링크": "https://neurips.cc/virtual/2025/poster/127625",
    },
    {
        "약어": "IP-DPP",
        "제목": "정보 보존 가능한 2단계 학습을 통한 긴 꼬리 인식",
        "코드": "https://github.com/fudong03/BNS_IPDPP",
        "동기": "2단계 분리 훈련에서 단순 균형 샘플링이 Stage 2에서 헤드 클래스 데이터를 버려 귀중한 테일 클래스 정보를 잃을 수 있음",
        "목표": "모든 클래스의 정보를 보존하면서 분류기 재훈련에서 다수 클래스 편향을 교정",
        "핵심 방법": "Stage 1: 클래스 내 특징 거리를 최소화하는 균형 이웃 샘플링(BNS); Stage 2: 클래스를 자연스럽게 균형화하면서 가장 정보적인 인스턴스를 유지하는 정보 보존 행렬식 점 과정(IP-DPP)",
        "평가-데이터": "CIFAR-10-LT, CIFAR-100-LT, ImageNet-LT, iNaturalist 2018",
        "평가-비교 모델": "KCL, TSC, SBCL, MiSLAS, BCL",
        "평가-실험 내용": "2단계 LT 인식; BNS와 IP-DPP 기여도 절제; 샘플링 전략 비교",
        "지표": "Top-1 정확도 (전체, many/medium/few 분할)",
        "주요 발견 및 기여": "IP-DPP는 모든 벤치마크에서 최첨단 달성; Stage 2에서 헤드 클래스 다양성 보존이 전체 정확도에 핵심적",
        "한계": "DPP 추론의 집합 크기에 대한 3차 복잡도; 대용량 데이터셋에 근사법 필요",
        "출처": "NeurIPS 2025",
        "연도": 2025,
        "PDF 링크": "https://arxiv.org/pdf/2510.08836",
    },
    {
        "약어": "IBCL",
        "제목": "이론적 근거를 갖춘 손실 함수를 이용한 향상된 균형 분류",
        "코드": None,
        "동기": "Logit-Adjusted(LA)와 클래스 가중 손실이 지배적이지만 강한 이론적 뒷받침 없음; 이론적으로 건전한 손실 계열 식별을 위한 H-일관성 경계 필요",
        "목표": "균형 분류 손실에 대한 H-일관성 경계 도출; 더 강한 이론적 보장을 가진 개선된 손실 계열(GLA, GCA) 제안",
        "핵심 방법": "전체 교차 엔트로피 계열로 LA 확장한 GLA(일반화 로짓 조정); 클래스 의존적 신뢰 마진을 가진 GCA(일반화 클래스 인식 가중); GCA는 심각한 불균형 하에서 1/√p_min 스케일링 H-일관성 경계 달성",
        "평가-데이터": "CIFAR-LT, ImageNet-LT",
        "평가-비교 모델": "표준 CE, LA 손실, 클래스 가중 CE",
        "평가-실험 내용": "다양한 IR에서 균형 다중 클래스 분류; 경계 이론적 분석",
        "지표": "균형 정확도, Macro-F1",
        "주요 발견 및 기여": "GCA는 심각한 불균형 하에서 가장 강한 이론적 보장(1/√p_min 스케일링); GLA는 일반 벤치마크에서 LA 초과",
        "한계": "LA 대비 실험적 향상이 미미함; 이론 결과가 특정 가설 클래스 조건 가정",
        "출처": "NeurIPS 2025",
        "연도": 2025,
        "PDF 링크": "https://arxiv.org/pdf/2512.23947",
    },
    {
        "약어": "OSB-SMOTE",
        "제목": "합성 오버샘플링을 이용한 불균형 분류의 집중 및 초과 위험 경계",
        "코드": None,
        "동기": "SMOTE는 불균형 분류에 널리 사용되지만 이론적 정당화가 부족; SMOTE 생성 데이터로 훈련된 분류기에 대한 집중 또는 초과 위험 보장이 없음",
        "목표": "SMOTE와 변형에 대한 집중 경계, 초과 위험 보장, 파라미터 안내를 포함하는 최초의 엄밀한 이론적 프레임워크 제공",
        "핵심 방법": "합성 소수 샘플 경험적 위험의 균일 집중 경계; 합성 오버샘플링으로 훈련된 커널 분류기를 위한 비모수적 초과 위험 보장; k-이웃과 혼합 계수 최적화를 위한 파라미터 안내",
        "평가-데이터": "표준 불균형 분류 데이터셋 (이론 검증)",
        "평가-비교 모델": "단순 오버샘플링, 오버샘플링 없음",
        "평가-실험 내용": "표준 불균형 데이터셋에서 실험 검증을 통한 이론 도출",
        "지표": "AUC, 균형 정확도 (실험); 집중 및 초과 위험 경계 (이론)",
        "주요 발견 및 기여": "SMOTE에 대한 최초의 집중 및 초과 위험 경계; 최적 SMOTE 파라미터 영역 식별; SMOTE 데이터로 훈련된 커널 분류기가 최적 비모수 수렴률로 수렴",
        "한계": "결과가 커널 분류기에 한정; 신경망 확장 미해결",
        "출처": "NeurIPS 2025",
        "연도": 2025,
        "PDF 링크": "https://arxiv.org/pdf/2510.20472",
    },
    {
        "약어": "ImGDA",
        "제목": "클래스 불균형 그래프 도메인 적응을 위한 이중 프로토타입 강화 대조 프레임워크",
        "코드": "https://github.com/maxin88scu/ImGDA",
        "동기": "소스 도메인에 클래스 불균형이 있을 때 그래프 도메인 적응이 실패—표준 정렬 절차가 희귀 소스 클래스를 헤드 타겟 클래스에 잘못 정렬",
        "목표": "이중 프로토타입 대조 학습으로 교차 그래프 도메인 적응 중 소스 도메인 클래스 불균형 교정",
        "핵심 방법": "클래스별 프로토타입 생성하는 이중 분기 그래프 인코더(로컬+글로벌); 소스 내 교차 분기 대조로 불균형 완화; 의사 레이블을 이용한 교차 도메인 대조로 도메인 불일치 감소",
        "평가-데이터": "인용 네트워크 변형 등 그래프 도메인 적응 벤치마크",
        "평가-비교 모델": "DANN, CDAN, UDAGCN, JHGDA 등 그래프 도메인 적응 방법",
        "평가-실험 내용": "클래스 불균형 소스 도메인 하에서 비지도 그래프 도메인 적응; 로컬 vs. 글로벌 프로토타입 기여도 절제",
        "지표": "Macro-F1, 노드 분류 정확도",
        "주요 발견 및 기여": "ImGDA는 모든 그래프 도메인 적응 기준선 초과; 이중 분기 프로토타입 생성이 교차 도메인 클래스 정렬에 핵심",
        "한계": "앵커 프로토타입 선택 필요 (앵커 품질에 민감); 비지도 타겟 설정으로 한정",
        "출처": "NeurIPS 2025",
        "연도": 2025,
        "PDF 링크": "https://openreview.net/pdf?id=QSK8VqiijI",
    },
    {
        "약어": "RLAL",
        "제목": "긴 꼬리 학습 재고찰: 아키텍처 관점에서의 통찰",
        "코드": None,
        "동기": "모든 기존 LT 방법은 네트워크 아키텍처를 고정하고 훈련 절차만 수정함; 아키텍처 자체가 불균형 편향의 원인인지 탐구되지 않았음",
        "목표": "위상, 합성곱 유형, 활성화 함수가 LT 성능에 미치는 영향 분석; 신경망 아키텍처 탐색으로 LT 인식 아키텍처 설계",
        "핵심 방법": "LT 강건성을 위한 신규 LT-AggConv, LT-HierConv 연산; LT 인식 탐색 공간과 비편향 탐색 전략을 가진 LT-DARTS; 발견된 아키텍처는 기존 손실/샘플링 방법과 직교적으로 결합 가능",
        "평가-데이터": "CIFAR-10-LT, CIFAR-100-LT, ImageNet-LT",
        "평가-비교 모델": "표준 ResNet, ResNeXt; LA 손실, MiSLAS와 결합 기준선",
        "평가-실험 내용": "LT 아키텍처 탐색; LT-AggConv/LT-HierConv 절제; 기존 LT 훈련 방법과 결합",
        "지표": "Top-1 정확도 (전체, many/medium/few 분할)",
        "주요 발견 및 기여": "아키텍처 설계는 LT 향상의 독립적이고 가산적인 원천; LT-DARTS 아키텍처가 방법 수준 향상과 결합",
        "한계": "NAS 탐색이 계산 비용이 큼; 발견된 아키텍처가 모든 IR에 일반화되지 않을 수 있음",
        "출처": "CIKM 2025",
        "연도": 2025,
        "PDF 링크": "https://arxiv.org/pdf/2411.06098",
    },
    {
        "약어": "GraphIAM",
        "제목": "GraphIAM: 속성 결측 그래프의 클래스 불균형 노드 분류 향상을 위한 2단계 알고리즘",
        "코드": None,
        "동기": "속성 결측 그래프에서 노드 분류는 이중으로 어려움: 결측 속성이 특징 품질을 저하, 클래스 불균형이 훈련을 다수 클래스로 편향; 소수 노드가 속성과 차수 모두 희소한 경향",
        "목표": "속성 불완전성과 클래스 불균형을 2단계 알고리즘으로 동시에 처리",
        "핵심 방법": "Stage 1: 이웃 집계와 의미론적 전파로 결측 속성 대치; Stage 2: 완성된 그래프에서 불균형 인식 노드 분류; 오류 전파 방지를 위한 단계 간 상호 정보 제공",
        "평가-데이터": "Cora, Citeseer 등 노드 분류 데이터셋 (속성 결측 및 클래스 불균형 조건 유도)",
        "평가-비교 모델": "GraphSMOTE, DPGNN, TAM 및 속성 대치 기준선",
        "평가-실험 내용": "속성 결측과 클래스 불균형 결합 조건에서 노드 분류",
        "지표": "Macro-F1, AUC",
        "주요 발견 및 기여": "GraphIAM은 모든 기준선 초과; 속성 결측과 불균형의 공동 고려가 각각 독립 처리보다 효과적",
        "한계": "2단계 파이프라인: Stage 1 대치가 나쁘면 Stage 2가 복구 불가; 주로 인용 네트워크에서 평가",
        "출처": "CIKM 2025",
        "연도": 2025,
        "PDF 링크": "https://www.cikm2025.org/program/accepted-papers",
    },
]


def add_pdf_link_column_and_rows(filepath, papers, is_korean=False):
    wb = openpyxl.load_workbook(filepath)
    ws = wb.active

    # Add 'PDF Link' column header at the end
    last_col = ws.max_column
    new_col = last_col + 1
    pdf_col_header = "PDF 링크" if is_korean else "PDF Link"
    ws.cell(row=1, column=new_col, value=pdf_col_header)

    # Apply basic header style to new column
    header_cell = ws.cell(row=1, column=new_col)
    header_cell.font = Font(bold=True)
    header_cell.fill = PatternFill(fill_type="solid", fgColor="D9D9D9")

    # Get column mapping from header row
    col_map = {}
    for cell in ws[1]:
        if cell.value:
            col_map[cell.value] = cell.column

    # Field mapping (EN col name → paper key, or KO col name → paper key)
    if is_korean:
        field_order = [
            ("약어", "약어"),
            ("제목", "제목"),
            ("코드", "코드"),
            ("동기", "동기"),
            ("목표", "목표"),
            ("핵심 방법", "핵심 방법"),
            ("평가-데이터", "평가-데이터"),
            ("평가-비교 모델", "평가-비교 모델"),
            ("평가-실험 내용", "평가-실험 내용"),
            ("지표", "지표"),
            ("주요 발견 및 기여", "주요 발견 및 기여"),
            ("한계", "한계"),
            ("출처", "출처"),
            ("연도", "연도"),
            ("PDF 링크", "PDF 링크"),
        ]
    else:
        field_order = [
            ("Abb.", "Abb."),
            ("Title", "Title"),
            ("Codes", "Codes"),
            ("Motivation", "Motivation"),
            ("Goal", "Goal"),
            ("Key methods", "Key methods"),
            ("Eval-Data", "Eval-Data"),
            ("Eval-Comparison Models", "Eval-Comparison Models"),
            ("Eval-Experiments", "Eval-Experiments"),
            ("Metrics", "Metrics"),
            ("Key findings", "Key findings"),
            ("Limitations", "Limitations"),
            ("Source", "Source"),
            ("Year", "Year"),
            ("PDF Link", "PDF Link"),
        ]

    # Update existing rows with PDF Link (fill None for existing papers)
    for row_idx in range(2, ws.max_row + 1):
        ws.cell(row=row_idx, column=new_col, value=None)

    # Append new paper rows
    start_row = ws.max_row + 1
    for paper in papers:
        row_idx = start_row
        for col_name, paper_key in field_order:
            if col_name in col_map:
                col_idx = col_map[col_name]
            else:
                col_idx = new_col  # for PDF link
            ws.cell(row=row_idx, column=col_idx, value=paper.get(paper_key))
        start_row += 1

    # Auto-width (approximate)
    for col_idx in range(1, ws.max_column + 1):
        max_len = 0
        col_letter = get_column_letter(col_idx)
        for cell in ws[col_letter]:
            if cell.value:
                max_len = max(max_len, len(str(cell.value)))
        ws.column_dimensions[col_letter].width = min(max(max_len, 10), 60)

    wb.save(filepath)
    print(f"Saved {filepath}: {ws.max_row - 1} data rows, {ws.max_column} columns")


if __name__ == "__main__":
    add_pdf_link_column_and_rows(
        "reference/paper_summary_en.xlsx", PAPERS_EN, is_korean=False)
    add_pdf_link_column_and_rows(
        "reference/paper_summary_ko.xlsx", PAPERS_KO, is_korean=True)
    print("Done.")
